-- Active: 1749847818946@@127.0.0.1@5432@postgres
CREATE SEQUENCE IF NOT EXISTS checklist_id_sequence START 1 INCREMENT 1;
CREATE SEQUENCE IF NOT EXISTS checklist_share_id_sequence START 1 INCREMENT 1;
CREATE SEQUENCE IF NOT EXISTS checklist_invite_id_sequence START 1 INCREMENT 1;
CREATE SEQUENCE IF NOT EXISTS checklist_item_id_sequence START 1 INCREMENT 1;
CREATE SEQUENCE IF NOT EXISTS checklist_item_row_id_sequence START 1 INCREMENT 1;
CREATE SEQUENCE IF NOT EXISTS template_id_sequence START 1 INCREMENT 1;
CREATE SEQUENCE IF NOT EXISTS template_row_id_sequence START 1 INCREMENT 1;
CREATE TABLE IF NOT EXISTS CHECKLIST (
    ID BIGINT PRIMARY KEY,
    OWNER VARCHAR(255) NOT NULL,
    NAME VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS CHECKLIST_ITEM (
    CHECKLIST_ITEM_ID BIGINT PRIMARY KEY,
    CHECKLIST_ID BIGINT NOT NULL,
    CHECKLIST_ITEM_NAME VARCHAR(255) NOT NULL,
    CHECKLIST_ITEM_COMPLETED BOOLEAN NOT NULL DEFAULT FALSE,
    POSITION DOUBLE PRECISION NOT NULL DEFAULT 0,
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (checklist_id) REFERENCES CHECKLIST (ID) ON DELETE CASCADE
);

-- Add updated_at column if it doesn't exist (for existing databases)
ALTER TABLE CHECKLIST_ITEM ADD COLUMN IF NOT EXISTS UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;

CREATE OR REPLACE VIEW CHECKLIST_ITEMS_ORDERED_VIEW AS
SELECT
    CHECKLIST_ID,
    CHECKLIST_ITEM_ID,
    CHECKLIST_ITEM_NAME,
    CHECKLIST_ITEM_COMPLETED,
    POSITION,
    ROW_NUMBER() OVER (
        PARTITION BY CHECKLIST_ID
        ORDER BY CHECKLIST_ITEM_COMPLETED ASC, POSITION ASC
    ) AS ORDER_NUMBER
FROM CHECKLIST_ITEM;

CREATE TABLE IF NOT EXISTS CHECKLIST_ITEM_ROW (
    CHECKLIST_ITEM_ROW_ID BIGINT PRIMARY KEY,
    CHECKLIST_ITEM_ID BIGINT NOT NULL,
    CHECKLIST_ITEM_ROW_NAME VARCHAR(255) NOT NULL,
    CHECKLIST_ITEM_ROW_COMPLETED BOOLEAN NOT NULL DEFAULT FALSE,
    FOREIGN KEY (CHECKLIST_ITEM_ID) REFERENCES CHECKLIST_ITEM (CHECKLIST_ITEM_ID) ON DELETE CASCADE);

-- User templates for reusable ingredient/item lists
CREATE TABLE IF NOT EXISTS TEMPLATE (
    ID BIGINT PRIMARY KEY DEFAULT NEXTVAL('template_id_sequence'),
    USER_ID VARCHAR(255) NOT NULL REFERENCES app_user(user_id) ON DELETE CASCADE,
    NAME VARCHAR(255) NOT NULL,
    DESCRIPTION TEXT,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(USER_ID, NAME)  -- No duplicate template names per user
);

-- Rows in a template (blueprint for checklist item rows)
CREATE TABLE IF NOT EXISTS TEMPLATE_ROW (
    ID BIGINT PRIMARY KEY DEFAULT NEXTVAL('template_row_id_sequence'),
    TEMPLATE_ID BIGINT NOT NULL REFERENCES TEMPLATE(ID) ON DELETE CASCADE,
    NAME VARCHAR(255) NOT NULL,
    POSITION DOUBLE PRECISION NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Index for efficient ordering queries by position
CREATE INDEX IF NOT EXISTS idx_checklist_item_position
  ON CHECKLIST_ITEM (CHECKLIST_ID, CHECKLIST_ITEM_COMPLETED, POSITION);

-- Indexes for efficient template queries
CREATE INDEX IF NOT EXISTS idx_template_user_id
  ON TEMPLATE (USER_ID);

CREATE INDEX IF NOT EXISTS idx_template_row_template_id
  ON TEMPLATE_ROW (TEMPLATE_ID);


CREATE TABLE IF NOT EXISTS CHECKLIST_SHARE (
    ID BIGINT PRIMARY KEY DEFAULT NEXTVAL('checklist_share_id_sequence'),
    CHECKLIST_ID BIGINT NOT NULL REFERENCES CHECKLIST(ID) ON DELETE CASCADE,
    SHARED_BY_USER_ID VARCHAR(255) NOT NULL,  -- Owner's Google ID
    SHARED_WITH_USER_ID VARCHAR(255) NOT NULL,  -- Recipient's Google ID
    PERMISSION_LEVEL VARCHAR(20) NOT NULL DEFAULT 'READ' CHECK (PERMISSION_LEVEL IN ('READ', 'WRITE', 'DELETE', 'SUPER')),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(CHECKLIST_ID, SHARED_WITH_USER_ID)  -- Prevent duplicate shares
);

CREATE TABLE IF NOT EXISTS CHECKLIST_INVITE (
    ID BIGINT PRIMARY KEY DEFAULT NEXTVAL('checklist_invite_id_sequence'),
    CHECKLIST_ID BIGINT NOT NULL REFERENCES CHECKLIST(ID) ON DELETE CASCADE,
    NAME VARCHAR(100) NULL,  -- Optional friendly name for the invite
    INVITE_TOKEN VARCHAR(64) NOT NULL UNIQUE,  -- Secure random token
    CREATED_BY VARCHAR(255) NOT NULL,  -- Google ID of creator
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    EXPIRES_AT TIMESTAMP NULL,  -- NULL means never expires
    CLAIMED_BY VARCHAR(255) NULL,  -- Google ID of claimer
    CLAIMED_AT TIMESTAMP NULL,
    IS_SINGLE_USE BOOLEAN NOT NULL DEFAULT TRUE,
    CHECK (CLAIMED_AT IS NULL OR CLAIMED_BY IS NOT NULL)  -- If claimed_at is set, claimed_by must be set
);

-- Index for fast lookup by token (most common query)
CREATE INDEX IF NOT EXISTS idx_checklist_invite_token ON CHECKLIST_INVITE(INVITE_TOKEN);

-- Index for finding active invites by checklist
CREATE INDEX IF NOT EXISTS idx_checklist_invite_active ON CHECKLIST_INVITE(CHECKLIST_ID, CLAIMED_AT, EXPIRES_AT) 
    WHERE CLAIMED_AT IS NULL;

ALTER TABLE CHECKLIST_INVITE ADD COLUMN IF NOT EXISTS NAME VARCHAR(255) NOT NULL DEFAULT '';

-- Session-based authentication tables
CREATE SEQUENCE IF NOT EXISTS session_id_sequence START 1 INCREMENT 1;

CREATE TABLE IF NOT EXISTS app_user (
    user_id VARCHAR(255) PRIMARY KEY,
    name VARCHAR(255),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);


CREATE TABLE IF NOT EXISTS user_session (
    id BIGINT PRIMARY KEY DEFAULT NEXTVAL('session_id_sequence'),
    session_id VARCHAR(255) NOT NULL UNIQUE,
    user_id VARCHAR(255) NOT NULL REFERENCES app_user(user_id) ON DELETE CASCADE,
    access_token_encrypted BYTEA NOT NULL,
    refresh_token_encrypted BYTEA NOT NULL,
    access_token_expires_at TIMESTAMP NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_activity_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    expires_at TIMESTAMP NOT NULL,
    is_invalidated BOOLEAN NOT NULL DEFAULT FALSE,
    invalidated_at TIMESTAMP,
    invalidation_reason VARCHAR(100)
);

-- Indexes for performance (partial indexes on active sessions only)
CREATE INDEX IF NOT EXISTS idx_session_session_id ON user_session(session_id) WHERE is_invalidated = FALSE;
CREATE INDEX IF NOT EXISTS idx_session_user_id ON user_session(user_id) WHERE is_invalidated = FALSE;
CREATE INDEX IF NOT EXISTS idx_session_expiry ON user_session(expires_at) WHERE is_invalidated = FALSE;
CREATE INDEX IF NOT EXISTS idx_session_last_activity ON user_session(last_activity_at) WHERE is_invalidated = FALSE;

-- Soft delete support for checklist items (undo functionality)
ALTER TABLE CHECKLIST_ITEM ADD COLUMN IF NOT EXISTS DELETED_AT TIMESTAMP NULL;
ALTER TABLE CHECKLIST_ITEM ADD COLUMN IF NOT EXISTS DELETED_BY VARCHAR(255) NULL;

-- Index for efficient querying of active (non-deleted) items
CREATE INDEX IF NOT EXISTS idx_checklist_item_active 
ON CHECKLIST_ITEM(CHECKLIST_ID, DELETED_AT) 
WHERE DELETED_AT IS NULL;

-- Index for cleanup job to find old soft-deleted items
CREATE INDEX IF NOT EXISTS idx_checklist_item_deleted 
ON CHECKLIST_ITEM(DELETED_AT) 
WHERE DELETED_AT IS NOT NULL;

-- Job lock table for coordinating background jobs in serverless/multi-instance environments
CREATE TABLE IF NOT EXISTS job_lock (
    job_name VARCHAR(100) PRIMARY KEY,
    last_run_at TIMESTAMP NOT NULL,
    locked_by VARCHAR(255) NULL,  -- Instance identifier that holds the lock
    locked_at TIMESTAMP NULL
);

-- Insert default row for cleanup job if it doesn't exist
INSERT INTO job_lock (job_name, last_run_at) 
VALUES ('soft_delete_cleanup', '1970-01-01 00:00:00')
ON CONFLICT (job_name) DO NOTHING;