// Package session provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package session

import (
	"context"
	"encoding/json"
	"fmt"
	"net/http"

	"github.com/gin-gonic/gin"
	strictgin "github.com/oapi-codegen/runtime/strictmiddleware/gin"
)

const (
	CookieAuthScopes = "CookieAuth.Scopes"
)

// ClientIdResponse Response containing a server-generated client ID
type ClientIdResponse struct {
	// ClientId Secure, server-validated client ID for SSE connections
	ClientId string `json:"clientId"`
}

// Error defines model for Error.
type Error struct {
	Message string `json:"message"`
}

// XClientId defines model for X-Client-Id.
type XClientId = string

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Generate server-side client ID
	// (POST /api/v1/session/client-id)
	GenerateClientId(c *gin.Context)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// GenerateClientId operation middleware
func (siw *ServerInterfaceWrapper) GenerateClientId(c *gin.Context) {

	c.Set(CookieAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GenerateClientId(c)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.POST(options.BaseURL+"/api/v1/session/client-id", wrapper.GenerateClientId)
}

type GenerateClientIdRequestObject struct {
}

type GenerateClientIdResponseObject interface {
	VisitGenerateClientIdResponse(w http.ResponseWriter) error
}

type GenerateClientId200JSONResponse ClientIdResponse

func (response GenerateClientId200JSONResponse) VisitGenerateClientIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GenerateClientId401JSONResponse Error

func (response GenerateClientId401JSONResponse) VisitGenerateClientIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type GenerateClientId500JSONResponse Error

func (response GenerateClientId500JSONResponse) VisitGenerateClientIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Generate server-side client ID
	// (POST /api/v1/session/client-id)
	GenerateClientId(ctx context.Context, request GenerateClientIdRequestObject) (GenerateClientIdResponseObject, error)
}

type StrictHandlerFunc = strictgin.StrictGinHandlerFunc
type StrictMiddlewareFunc = strictgin.StrictGinMiddlewareFunc

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
}

// GenerateClientId operation middleware
func (sh *strictHandler) GenerateClientId(ctx *gin.Context) {
	var request GenerateClientIdRequestObject

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GenerateClientId(ctx, request.(GenerateClientIdRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GenerateClientId")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(GenerateClientIdResponseObject); ok {
		if err := validResponse.VisitGenerateClientIdResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}
