openapi: 3.0.3
info:
  title: Checklist Service API
  description: OpenAPI specification for the Checklist service.
  version: 1.0.0
paths:
  /:
    get:
      summary: Health check
      operationId: healthCheck
      tags:
        - health
      responses:
        '200':
          description: Server is healthy
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: ok
  /api/v1/checklists:
    get:
      summary: List all checklists
      operationId: listChecklists
      tags:
        - checklist
      responses:
        '200':
          description: A list of checklist items
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ChecklistResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

    post:
      summary: Create a new checklist
      operationId: createChecklist
      tags:
        - checklist
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateChecklistRequest'
      responses:
        '201':
          description: Checklist created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ChecklistResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '400':
          description: Validation error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /api/v1/checklists/{checklistId}:
    get:
      summary: Get a checklist
      operationId: getChecklist
      tags:
        - checklist
      parameters:
        - name: checklistId
          in: path
          required: true
          schema:
            type: number
            x-go-type: uint
            minimum: 1
            format: int64
          description: Checklist ID
      responses:
        '200':
          description: A checklist item
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ChecklistResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: Checklist not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

    put:
      summary: Update a checklist
      operationId: updateChecklist
      tags:
        - checklist
      parameters:
        - name: checklistId
          in: path
          required: true
          schema:
            type: number
            x-go-type: uint
            minimum: 1
            format: int64
          description: Checklist ID
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateChecklistRequest'
      responses:
        '200':
          description: A checklist item
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ChecklistResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: Checklist not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    delete:
      summary: Delete a checklist
      operationId: deleteChecklist
      tags:
        - checklist
      parameters:
        - name: checklistId
          in: path
          required: true
          schema:
            type: number
            x-go-type: uint
            minimum: 1
            format: int64
          description: Checklist ID
      responses:
        '204':
          description: Checklist deleted
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ChecklistResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: Checklist not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /api/v1/checklists/{checklistId}/items:
    get:
      summary: List checklist items
      operationId: listChecklistItems
      tags:
        - checklistItem
      parameters:
        - name: checklistId
          in: path
          required: true
          schema:
            type: number
            x-go-type: uint
            minimum: 1
            format: int64
          description: Checklist ID
        - name: sort
          in: query
          schema:
            type: string
            enum:
              - asc
              - desc
          description: Sort order
        - name: completed
          in: query
          schema:
            type: boolean
          description: Filter by completed status
      responses:
        '200':
          description: A list of checklist items
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ChecklistItemResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

    post:
      summary: Create a checklist item
      operationId: createChecklistItem
      tags:
        - checklistItem
      parameters:
        - name: checklistId
          in: path
          required: true
          schema:
            type: number
            x-go-type: uint
            minimum: 1
            format: int64
          description: Checklist ID
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateChecklistItemRequest'
      responses:
        '201':
          description: Checklist item created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ChecklistItemResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /api/v1/checklists/{checklistId}/items/{itemId}:
    get:
      summary: Get a checklist item
      operationId: getChecklistItem
      tags:
        - checklistItem
      parameters:
        - name: checklistId
          in: path
          required: true
          schema:
            type: number
            x-go-type: uint
            minimum: 1
            format: int64
          description: Checklist ID
        - name: itemId
          in: path
          required: true
          schema:
            type: number
            x-go-type: uint
            minimum: 1
            format: int64
            description: Checklist item id
      responses:
        '200':
           description: "Successful request"
           content:
              application/json:
                  schema:
                    $ref: '#/components/schemas/ChecklistItemResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: Checklist item or checklist not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    delete:
      summary: Delete a checklist item
      operationId: deleteChecklistItem
      tags:
        - checklistItem
      parameters:
        - name: checklistId
          in: path
          required: true
          schema:
            type: number
            x-go-type: uint
            minimum: 1
            format: int64
          description: Checklist ID
        - name: itemId
          in: path
          required: true
          schema:
            type: number
            x-go-type: uint
            minimum: 1
            format: int64
            description: Checklist item id
      responses:
        '204':
          description: Checklist item deleted
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ChecklistItemResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: Checklist item or checklist not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    put:
      summary: Update a checklist item
      operationId: updateChecklistItem
      tags:
        - checklistItem
      parameters:
        - name: checklistId
          in: path
          required: true
          schema:
            type: number
            x-go-type: uint
            minimum: 1
            format: int64
          description: Checklist ID
        - name: itemId
          in: path
          required: true
          schema:
            type: number
            x-go-type: uint
            minimum: 1
            format: int64
            description: Checklist item id
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateChecklistItemRequest'
      responses:
        '200':
              description: Checklist item updated
              content:
                application/json:
                  schema:
                    $ref: '#/components/schemas/ChecklistItemResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        
      description: Checklist item or checklist not found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'


  /api/v1/checklists/{checklistId}/items/{itemId}/change-order:
    patch:
      summary: Change checklist item order
      operationId: changeChecklistItemOrder
      tags:
        - checklistItem
      parameters:
        - name: checklistId
          in: path
          required: true
          schema:
            type: number
            x-go-type: uint
            minimum: 1
            format: int64
          description: checklist ID
        - name: itemId
          in: path
          required: true
          schema:
            type: number
            x-go-type: uint
            minimum: 1
            format: int64
          description: Checklist item id
        - name: sortOrder
          in: query
          schema:
            type: string
            enum: [asc, desc]
            default: asc
          required: false
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
               - newOrderNumber
              properties:
                newOrderNumber:
                  type: number
                  x-go-type: uint
                  format: int64
                  minimum: 1
      responses:
        '200':
          description: Successfully updated order number for checklist item
          content:
            application/json:
              schema:
                type: object
                properties:
                  oldOrderNumber:
                    type: number
                    x-go-type: uint
                    format: int64
                    minimum: 1
                  newOrderNumber:
                    type: number
                    x-go-type: uint
                    format: int64
                    minimum: 1
        '404':
          description: checklist item or checklist not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '400':
          description: Validation error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /api/v1/checklists/{checklistId}/items/{itemId}/rows:
    post:
      summary: Create a checklist item row
      operationId: createChecklistItemRow
      tags:
        - checklistItem
      parameters:
        - name: checklistId
          in: path
          required: true
          schema:
            type: number
            x-go-type: uint
            minimum: 1
            format: int64
          description: Checklist ID
        - name: itemId
          in: path
          required: true
          schema:
            type: number
            x-go-type: uint
            minimum: 1
            format: int64
          description: Checklist item id
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateChecklistItemRowRequest'
      responses:
        '201':
          description: Checklist item row created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ChecklistItemRowResponse'
        '404':
          description: Checklist item or checklist not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '400':
          description: Validation error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'



components:
  schemas:
    Error:
      type: object
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
          nullable: false
          minLength: 0
      required:
        - code
        - message
    CreateChecklistItemRequest:
      type: object
      properties:
        name:
          type: string
          nullable: false
          minLength: 1
        rows:
            type: array
            items:
                $ref: '#/components/schemas/CreateOrUpdateChecklistItemRowRequest'
      required:
        - name
    UpdateChecklistItemRequest:
      type: object
      properties:
        name:
          type: string
          nullable: false
          minLength: 1
        completed:
          type: boolean
          nullable: false
        rows:
          type: array
          items:
            type: object
            properties:
              id:
                type: integer
                x-go-type: uint
                format: int32
                nullable: false
                minimum: 1
              name:
                type: string
                nullable: false
                minLength: 1
              completed:
                type: boolean
                nullable: true
                default: false
            required:
              - name
              - completed
              - id
      required:
        - name
        - completed
        - rows
    ChecklistItemResponse:
      type: object
      properties:
        id:
          type: number
          x-go-type: uint
          nullable: false
          minimum: 1
          format: int64
        name:
          type: string
          nullable: false
          minLength: 1
        completed:
          type: boolean
          nullable: false
          default: false
        orderNumber:
          type: number
          x-go-type: uint
          nullable: false
          minimum: 1
          format: int64
        rows:
          type: array
          items:
            $ref: '#/components/schemas/ChecklistItemRowResponse'
      required:
        - name
        - completed
        - id
        - orderNumber
        - rows
    ChecklistItemRowResponse:
      type: object
      properties:
        id:
          type: number
          format: int64
          minimum: 0
          x-go-type: uint
          nullable: false
        name:
          type: string
          nullable: false
          minLength: 1
        completed:
          type: boolean
          nullable: true
          default: false
      required:
        - id
        - name
        - completed
    CreateOrUpdateChecklistItemRowRequest:
      type: object
      properties:
        name:
          type: string
          nullable: false
          minLength: 1
        completed:
          type: boolean
          nullable: true
          default: false
      required:
        - name
        - completed
    CreateChecklistItemRowRequest:
      allOf:
        - $ref: '#/components/schemas/CreateOrUpdateChecklistItemRowRequest'
    CreateChecklistRequest:
      type: object
      properties:
        name:
          type: string
          nullable: false
          minLength: 1
      required:
        - name
    ChecklistResponse:
      type: object
      properties:
        id:
          type: number
          x-go-type: uint
          nullable: false
          format: int64
          minimum: 1
        name:
          type: string
          nullable: false
          minLength: 1
        items:
          type: array
          items:
            $ref: '#/components/schemas/ChecklistItemResponse'
      required:
        - name
        - id

