// Package checklist provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package checklist

import (
	"context"
	"encoding/json"
	"fmt"
	"net/http"

	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
	strictgin "github.com/oapi-codegen/runtime/strictmiddleware/gin"
)

// ChecklistItemResponse defines model for ChecklistItemResponse.
type ChecklistItemResponse struct {
	Completed   bool                       `json:"completed"`
	Id          uint                       `json:"id"`
	Name        string                     `json:"name"`
	OrderNumber uint                       `json:"orderNumber"`
	Rows        []ChecklistItemRowResponse `json:"rows"`
}

// ChecklistItemRowResponse defines model for ChecklistItemRowResponse.
type ChecklistItemRowResponse struct {
	Completed *bool  `json:"completed"`
	Id        uint   `json:"id"`
	Name      string `json:"name"`
}

// ChecklistResponse defines model for ChecklistResponse.
type ChecklistResponse struct {
	Id    uint                     `json:"id"`
	Items *[]ChecklistItemResponse `json:"items,omitempty"`
	Name  string                   `json:"name"`
}

// CreateChecklistRequest defines model for CreateChecklistRequest.
type CreateChecklistRequest struct {
	Name string `json:"name"`
}

// Error defines model for Error.
type Error struct {
	Code    int32  `json:"code"`
	Message string `json:"message"`
}

// CreateChecklistJSONRequestBody defines body for CreateChecklist for application/json ContentType.
type CreateChecklistJSONRequestBody = CreateChecklistRequest

// UpdateChecklistJSONRequestBody defines body for UpdateChecklist for application/json ContentType.
type UpdateChecklistJSONRequestBody = CreateChecklistRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// List all checklists
	// (GET /api/v1/checklists)
	ListChecklists(c *gin.Context)
	// Create a new checklist
	// (POST /api/v1/checklists)
	CreateChecklist(c *gin.Context)
	// Delete a checklist
	// (DELETE /api/v1/checklists/{checklistId})
	DeleteChecklist(c *gin.Context, checklistId uint)
	// Get a checklist
	// (GET /api/v1/checklists/{checklistId})
	GetChecklist(c *gin.Context, checklistId uint)
	// Update a checklist
	// (PUT /api/v1/checklists/{checklistId})
	UpdateChecklist(c *gin.Context, checklistId uint)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// ListChecklists operation middleware
func (siw *ServerInterfaceWrapper) ListChecklists(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListChecklists(c)
}

// CreateChecklist operation middleware
func (siw *ServerInterfaceWrapper) CreateChecklist(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateChecklist(c)
}

// DeleteChecklist operation middleware
func (siw *ServerInterfaceWrapper) DeleteChecklist(c *gin.Context) {

	var err error

	// ------------- Path parameter "checklistId" -------------
	var checklistId uint

	err = runtime.BindStyledParameterWithOptions("simple", "checklistId", c.Param("checklistId"), &checklistId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter checklistId: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DeleteChecklist(c, checklistId)
}

// GetChecklist operation middleware
func (siw *ServerInterfaceWrapper) GetChecklist(c *gin.Context) {

	var err error

	// ------------- Path parameter "checklistId" -------------
	var checklistId uint

	err = runtime.BindStyledParameterWithOptions("simple", "checklistId", c.Param("checklistId"), &checklistId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter checklistId: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetChecklist(c, checklistId)
}

// UpdateChecklist operation middleware
func (siw *ServerInterfaceWrapper) UpdateChecklist(c *gin.Context) {

	var err error

	// ------------- Path parameter "checklistId" -------------
	var checklistId uint

	err = runtime.BindStyledParameterWithOptions("simple", "checklistId", c.Param("checklistId"), &checklistId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter checklistId: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.UpdateChecklist(c, checklistId)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.GET(options.BaseURL+"/api/v1/checklists", wrapper.ListChecklists)
	router.POST(options.BaseURL+"/api/v1/checklists", wrapper.CreateChecklist)
	router.DELETE(options.BaseURL+"/api/v1/checklists/:checklistId", wrapper.DeleteChecklist)
	router.GET(options.BaseURL+"/api/v1/checklists/:checklistId", wrapper.GetChecklist)
	router.PUT(options.BaseURL+"/api/v1/checklists/:checklistId", wrapper.UpdateChecklist)
}

type ListChecklistsRequestObject struct {
}

type ListChecklistsResponseObject interface {
	VisitListChecklistsResponse(w http.ResponseWriter) error
}

type ListChecklists200JSONResponse []ChecklistResponse

func (response ListChecklists200JSONResponse) VisitListChecklistsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type ListChecklists400JSONResponse Error

func (response ListChecklists400JSONResponse) VisitListChecklistsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type ListChecklists500JSONResponse Error

func (response ListChecklists500JSONResponse) VisitListChecklistsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type CreateChecklistRequestObject struct {
	Body *CreateChecklistJSONRequestBody
}

type CreateChecklistResponseObject interface {
	VisitCreateChecklistResponse(w http.ResponseWriter) error
}

type CreateChecklist201JSONResponse ChecklistResponse

func (response CreateChecklist201JSONResponse) VisitCreateChecklistResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type CreateChecklist400JSONResponse Error

func (response CreateChecklist400JSONResponse) VisitCreateChecklistResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type CreateChecklist500JSONResponse Error

func (response CreateChecklist500JSONResponse) VisitCreateChecklistResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type DeleteChecklistRequestObject struct {
	ChecklistId uint `json:"checklistId"`
}

type DeleteChecklistResponseObject interface {
	VisitDeleteChecklistResponse(w http.ResponseWriter) error
}

type DeleteChecklist204JSONResponse ChecklistResponse

func (response DeleteChecklist204JSONResponse) VisitDeleteChecklistResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(204)

	return json.NewEncoder(w).Encode(response)
}

type DeleteChecklist404JSONResponse Error

func (response DeleteChecklist404JSONResponse) VisitDeleteChecklistResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type DeleteChecklist500JSONResponse Error

func (response DeleteChecklist500JSONResponse) VisitDeleteChecklistResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetChecklistRequestObject struct {
	ChecklistId uint `json:"checklistId"`
}

type GetChecklistResponseObject interface {
	VisitGetChecklistResponse(w http.ResponseWriter) error
}

type GetChecklist200JSONResponse ChecklistResponse

func (response GetChecklist200JSONResponse) VisitGetChecklistResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetChecklist400JSONResponse Error

func (response GetChecklist400JSONResponse) VisitGetChecklistResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type GetChecklist404JSONResponse Error

func (response GetChecklist404JSONResponse) VisitGetChecklistResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type GetChecklist500JSONResponse Error

func (response GetChecklist500JSONResponse) VisitGetChecklistResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type UpdateChecklistRequestObject struct {
	ChecklistId uint `json:"checklistId"`
	Body        *UpdateChecklistJSONRequestBody
}

type UpdateChecklistResponseObject interface {
	VisitUpdateChecklistResponse(w http.ResponseWriter) error
}

type UpdateChecklist200JSONResponse ChecklistResponse

func (response UpdateChecklist200JSONResponse) VisitUpdateChecklistResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type UpdateChecklist400JSONResponse Error

func (response UpdateChecklist400JSONResponse) VisitUpdateChecklistResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type UpdateChecklist404JSONResponse Error

func (response UpdateChecklist404JSONResponse) VisitUpdateChecklistResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type UpdateChecklist500JSONResponse Error

func (response UpdateChecklist500JSONResponse) VisitUpdateChecklistResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// List all checklists
	// (GET /api/v1/checklists)
	ListChecklists(ctx context.Context, request ListChecklistsRequestObject) (ListChecklistsResponseObject, error)
	// Create a new checklist
	// (POST /api/v1/checklists)
	CreateChecklist(ctx context.Context, request CreateChecklistRequestObject) (CreateChecklistResponseObject, error)
	// Delete a checklist
	// (DELETE /api/v1/checklists/{checklistId})
	DeleteChecklist(ctx context.Context, request DeleteChecklistRequestObject) (DeleteChecklistResponseObject, error)
	// Get a checklist
	// (GET /api/v1/checklists/{checklistId})
	GetChecklist(ctx context.Context, request GetChecklistRequestObject) (GetChecklistResponseObject, error)
	// Update a checklist
	// (PUT /api/v1/checklists/{checklistId})
	UpdateChecklist(ctx context.Context, request UpdateChecklistRequestObject) (UpdateChecklistResponseObject, error)
}

type StrictHandlerFunc = strictgin.StrictGinHandlerFunc
type StrictMiddlewareFunc = strictgin.StrictGinMiddlewareFunc

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
}

// ListChecklists operation middleware
func (sh *strictHandler) ListChecklists(ctx *gin.Context) {
	var request ListChecklistsRequestObject

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.ListChecklists(ctx, request.(ListChecklistsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListChecklists")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(ListChecklistsResponseObject); ok {
		if err := validResponse.VisitListChecklistsResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateChecklist operation middleware
func (sh *strictHandler) CreateChecklist(ctx *gin.Context) {
	var request CreateChecklistRequestObject

	var body CreateChecklistJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		ctx.Status(http.StatusBadRequest)
		ctx.Error(err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.CreateChecklist(ctx, request.(CreateChecklistRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateChecklist")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(CreateChecklistResponseObject); ok {
		if err := validResponse.VisitCreateChecklistResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeleteChecklist operation middleware
func (sh *strictHandler) DeleteChecklist(ctx *gin.Context, checklistId uint) {
	var request DeleteChecklistRequestObject

	request.ChecklistId = checklistId

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteChecklist(ctx, request.(DeleteChecklistRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteChecklist")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(DeleteChecklistResponseObject); ok {
		if err := validResponse.VisitDeleteChecklistResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetChecklist operation middleware
func (sh *strictHandler) GetChecklist(ctx *gin.Context, checklistId uint) {
	var request GetChecklistRequestObject

	request.ChecklistId = checklistId

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetChecklist(ctx, request.(GetChecklistRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetChecklist")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(GetChecklistResponseObject); ok {
		if err := validResponse.VisitGetChecklistResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// UpdateChecklist operation middleware
func (sh *strictHandler) UpdateChecklist(ctx *gin.Context, checklistId uint) {
	var request UpdateChecklistRequestObject

	request.ChecklistId = checklistId

	var body UpdateChecklistJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		ctx.Status(http.StatusBadRequest)
		ctx.Error(err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.UpdateChecklist(ctx, request.(UpdateChecklistRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UpdateChecklist")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(UpdateChecklistResponseObject); ok {
		if err := validResponse.VisitUpdateChecklistResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}
