// Package checklist provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package checklist

import (
	"context"
	"encoding/json"
	"fmt"
	"net/http"

	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
	strictgin "github.com/oapi-codegen/runtime/strictmiddleware/gin"
)

// ChecklistItemResponse defines model for ChecklistItemResponse.
type ChecklistItemResponse struct {
	Completed   bool                       `json:"completed"`
	Id          uint                       `json:"id"`
	Name        string                     `json:"name"`
	OrderNumber uint                       `json:"orderNumber"`
	Rows        []ChecklistItemRowResponse `json:"rows"`
}

// ChecklistItemRowResponse defines model for ChecklistItemRowResponse.
type ChecklistItemRowResponse struct {
	Completed *bool  `json:"completed"`
	Id        uint   `json:"id"`
	Name      string `json:"name"`
}

// ChecklistResponse defines model for ChecklistResponse.
type ChecklistResponse struct {
	Id    uint                     `json:"id"`
	Items *[]ChecklistItemResponse `json:"items,omitempty"`
	Name  string                   `json:"name"`
}

// ChecklistUpdateAndCreateRequest defines model for ChecklistUpdateAndCreateRequest.
type ChecklistUpdateAndCreateRequest struct {
	Name string `json:"name"`
}

// CreateChecklistRequest defines model for CreateChecklistRequest.
type CreateChecklistRequest = ChecklistUpdateAndCreateRequest

// Error defines model for Error.
type Error struct {
	Message string `json:"message"`
}

// XClientId defines model for X-Client-Id.
type XClientId = string

// GetAllChecklistsParams defines parameters for GetAllChecklists.
type GetAllChecklistsParams struct {
	// XClientId Client identifier sent by frontend in headers
	XClientId *XClientId `json:"X-Client-Id,omitempty"`
}

// CreateChecklistParams defines parameters for CreateChecklist.
type CreateChecklistParams struct {
	// XClientId Client identifier sent by frontend in headers
	XClientId *XClientId `json:"X-Client-Id,omitempty"`
}

// DeleteChecklistByIdParams defines parameters for DeleteChecklistById.
type DeleteChecklistByIdParams struct {
	// XClientId Client identifier sent by frontend in headers
	XClientId *XClientId `json:"X-Client-Id,omitempty"`
}

// GetChecklistByIdParams defines parameters for GetChecklistById.
type GetChecklistByIdParams struct {
	// XClientId Client identifier sent by frontend in headers
	XClientId *XClientId `json:"X-Client-Id,omitempty"`
}

// UpdateChecklistByIdParams defines parameters for UpdateChecklistById.
type UpdateChecklistByIdParams struct {
	// XClientId Client identifier sent by frontend in headers
	XClientId *XClientId `json:"X-Client-Id,omitempty"`
}

// CreateChecklistJSONRequestBody defines body for CreateChecklist for application/json ContentType.
type CreateChecklistJSONRequestBody = CreateChecklistRequest

// UpdateChecklistByIdJSONRequestBody defines body for UpdateChecklistById for application/json ContentType.
type UpdateChecklistByIdJSONRequestBody = CreateChecklistRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Get all checklists
	// (GET /api/v1/checklists)
	GetAllChecklists(c *gin.Context, params GetAllChecklistsParams)
	// Create a new checklist
	// (POST /api/v1/checklists)
	CreateChecklist(c *gin.Context, params CreateChecklistParams)
	// Delete checklist by ID
	// (DELETE /api/v1/checklists/{checklistId})
	DeleteChecklistById(c *gin.Context, checklistId uint, params DeleteChecklistByIdParams)
	// Get checklist by ID
	// (GET /api/v1/checklists/{checklistId})
	GetChecklistById(c *gin.Context, checklistId uint, params GetChecklistByIdParams)
	// Update checklist by ID
	// (PUT /api/v1/checklists/{checklistId})
	UpdateChecklistById(c *gin.Context, checklistId uint, params UpdateChecklistByIdParams)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// GetAllChecklists operation middleware
func (siw *ServerInterfaceWrapper) GetAllChecklists(c *gin.Context) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetAllChecklistsParams

	headers := c.Request.Header

	// ------------- Optional header parameter "X-Client-Id" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Client-Id")]; found {
		var XClientId XClientId
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandler(c, fmt.Errorf("Expected one value for X-Client-Id, got %d", n), http.StatusBadRequest)
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Client-Id", valueList[0], &XClientId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false})
		if err != nil {
			siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter X-Client-Id: %w", err), http.StatusBadRequest)
			return
		}

		params.XClientId = &XClientId

	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetAllChecklists(c, params)
}

// CreateChecklist operation middleware
func (siw *ServerInterfaceWrapper) CreateChecklist(c *gin.Context) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params CreateChecklistParams

	headers := c.Request.Header

	// ------------- Optional header parameter "X-Client-Id" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Client-Id")]; found {
		var XClientId XClientId
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandler(c, fmt.Errorf("Expected one value for X-Client-Id, got %d", n), http.StatusBadRequest)
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Client-Id", valueList[0], &XClientId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false})
		if err != nil {
			siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter X-Client-Id: %w", err), http.StatusBadRequest)
			return
		}

		params.XClientId = &XClientId

	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateChecklist(c, params)
}

// DeleteChecklistById operation middleware
func (siw *ServerInterfaceWrapper) DeleteChecklistById(c *gin.Context) {

	var err error

	// ------------- Path parameter "checklistId" -------------
	var checklistId uint

	err = runtime.BindStyledParameterWithOptions("simple", "checklistId", c.Param("checklistId"), &checklistId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter checklistId: %w", err), http.StatusBadRequest)
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params DeleteChecklistByIdParams

	headers := c.Request.Header

	// ------------- Optional header parameter "X-Client-Id" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Client-Id")]; found {
		var XClientId XClientId
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandler(c, fmt.Errorf("Expected one value for X-Client-Id, got %d", n), http.StatusBadRequest)
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Client-Id", valueList[0], &XClientId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false})
		if err != nil {
			siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter X-Client-Id: %w", err), http.StatusBadRequest)
			return
		}

		params.XClientId = &XClientId

	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DeleteChecklistById(c, checklistId, params)
}

// GetChecklistById operation middleware
func (siw *ServerInterfaceWrapper) GetChecklistById(c *gin.Context) {

	var err error

	// ------------- Path parameter "checklistId" -------------
	var checklistId uint

	err = runtime.BindStyledParameterWithOptions("simple", "checklistId", c.Param("checklistId"), &checklistId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter checklistId: %w", err), http.StatusBadRequest)
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetChecklistByIdParams

	headers := c.Request.Header

	// ------------- Optional header parameter "X-Client-Id" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Client-Id")]; found {
		var XClientId XClientId
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandler(c, fmt.Errorf("Expected one value for X-Client-Id, got %d", n), http.StatusBadRequest)
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Client-Id", valueList[0], &XClientId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false})
		if err != nil {
			siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter X-Client-Id: %w", err), http.StatusBadRequest)
			return
		}

		params.XClientId = &XClientId

	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetChecklistById(c, checklistId, params)
}

// UpdateChecklistById operation middleware
func (siw *ServerInterfaceWrapper) UpdateChecklistById(c *gin.Context) {

	var err error

	// ------------- Path parameter "checklistId" -------------
	var checklistId uint

	err = runtime.BindStyledParameterWithOptions("simple", "checklistId", c.Param("checklistId"), &checklistId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter checklistId: %w", err), http.StatusBadRequest)
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params UpdateChecklistByIdParams

	headers := c.Request.Header

	// ------------- Optional header parameter "X-Client-Id" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Client-Id")]; found {
		var XClientId XClientId
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandler(c, fmt.Errorf("Expected one value for X-Client-Id, got %d", n), http.StatusBadRequest)
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Client-Id", valueList[0], &XClientId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false})
		if err != nil {
			siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter X-Client-Id: %w", err), http.StatusBadRequest)
			return
		}

		params.XClientId = &XClientId

	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.UpdateChecklistById(c, checklistId, params)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.GET(options.BaseURL+"/api/v1/checklists", wrapper.GetAllChecklists)
	router.POST(options.BaseURL+"/api/v1/checklists", wrapper.CreateChecklist)
	router.DELETE(options.BaseURL+"/api/v1/checklists/:checklistId", wrapper.DeleteChecklistById)
	router.GET(options.BaseURL+"/api/v1/checklists/:checklistId", wrapper.GetChecklistById)
	router.PUT(options.BaseURL+"/api/v1/checklists/:checklistId", wrapper.UpdateChecklistById)
}

type GetAllChecklistsRequestObject struct {
	Params GetAllChecklistsParams
}

type GetAllChecklistsResponseObject interface {
	VisitGetAllChecklistsResponse(w http.ResponseWriter) error
}

type GetAllChecklists200JSONResponse []ChecklistResponse

func (response GetAllChecklists200JSONResponse) VisitGetAllChecklistsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetAllChecklists400JSONResponse Error

func (response GetAllChecklists400JSONResponse) VisitGetAllChecklistsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type GetAllChecklists500JSONResponse Error

func (response GetAllChecklists500JSONResponse) VisitGetAllChecklistsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type CreateChecklistRequestObject struct {
	Params CreateChecklistParams
	Body   *CreateChecklistJSONRequestBody
}

type CreateChecklistResponseObject interface {
	VisitCreateChecklistResponse(w http.ResponseWriter) error
}

type CreateChecklist201JSONResponse ChecklistResponse

func (response CreateChecklist201JSONResponse) VisitCreateChecklistResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type CreateChecklist400JSONResponse Error

func (response CreateChecklist400JSONResponse) VisitCreateChecklistResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type CreateChecklist500JSONResponse Error

func (response CreateChecklist500JSONResponse) VisitCreateChecklistResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type DeleteChecklistByIdRequestObject struct {
	ChecklistId uint `json:"checklistId"`
	Params      DeleteChecklistByIdParams
}

type DeleteChecklistByIdResponseObject interface {
	VisitDeleteChecklistByIdResponse(w http.ResponseWriter) error
}

type DeleteChecklistById204JSONResponse ChecklistResponse

func (response DeleteChecklistById204JSONResponse) VisitDeleteChecklistByIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(204)

	return json.NewEncoder(w).Encode(response)
}

type DeleteChecklistById404JSONResponse Error

func (response DeleteChecklistById404JSONResponse) VisitDeleteChecklistByIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type DeleteChecklistById500JSONResponse Error

func (response DeleteChecklistById500JSONResponse) VisitDeleteChecklistByIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetChecklistByIdRequestObject struct {
	ChecklistId uint `json:"checklistId"`
	Params      GetChecklistByIdParams
}

type GetChecklistByIdResponseObject interface {
	VisitGetChecklistByIdResponse(w http.ResponseWriter) error
}

type GetChecklistById200JSONResponse ChecklistResponse

func (response GetChecklistById200JSONResponse) VisitGetChecklistByIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetChecklistById400JSONResponse Error

func (response GetChecklistById400JSONResponse) VisitGetChecklistByIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type GetChecklistById404JSONResponse Error

func (response GetChecklistById404JSONResponse) VisitGetChecklistByIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type GetChecklistById500JSONResponse Error

func (response GetChecklistById500JSONResponse) VisitGetChecklistByIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type UpdateChecklistByIdRequestObject struct {
	ChecklistId uint `json:"checklistId"`
	Params      UpdateChecklistByIdParams
	Body        *UpdateChecklistByIdJSONRequestBody
}

type UpdateChecklistByIdResponseObject interface {
	VisitUpdateChecklistByIdResponse(w http.ResponseWriter) error
}

type UpdateChecklistById200JSONResponse ChecklistResponse

func (response UpdateChecklistById200JSONResponse) VisitUpdateChecklistByIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type UpdateChecklistById400JSONResponse Error

func (response UpdateChecklistById400JSONResponse) VisitUpdateChecklistByIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type UpdateChecklistById404JSONResponse Error

func (response UpdateChecklistById404JSONResponse) VisitUpdateChecklistByIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type UpdateChecklistById500JSONResponse Error

func (response UpdateChecklistById500JSONResponse) VisitUpdateChecklistByIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Get all checklists
	// (GET /api/v1/checklists)
	GetAllChecklists(ctx context.Context, request GetAllChecklistsRequestObject) (GetAllChecklistsResponseObject, error)
	// Create a new checklist
	// (POST /api/v1/checklists)
	CreateChecklist(ctx context.Context, request CreateChecklistRequestObject) (CreateChecklistResponseObject, error)
	// Delete checklist by ID
	// (DELETE /api/v1/checklists/{checklistId})
	DeleteChecklistById(ctx context.Context, request DeleteChecklistByIdRequestObject) (DeleteChecklistByIdResponseObject, error)
	// Get checklist by ID
	// (GET /api/v1/checklists/{checklistId})
	GetChecklistById(ctx context.Context, request GetChecklistByIdRequestObject) (GetChecklistByIdResponseObject, error)
	// Update checklist by ID
	// (PUT /api/v1/checklists/{checklistId})
	UpdateChecklistById(ctx context.Context, request UpdateChecklistByIdRequestObject) (UpdateChecklistByIdResponseObject, error)
}

type StrictHandlerFunc = strictgin.StrictGinHandlerFunc
type StrictMiddlewareFunc = strictgin.StrictGinMiddlewareFunc

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
}

// GetAllChecklists operation middleware
func (sh *strictHandler) GetAllChecklists(ctx *gin.Context, params GetAllChecklistsParams) {
	var request GetAllChecklistsRequestObject

	request.Params = params

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetAllChecklists(ctx, request.(GetAllChecklistsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetAllChecklists")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(GetAllChecklistsResponseObject); ok {
		if err := validResponse.VisitGetAllChecklistsResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateChecklist operation middleware
func (sh *strictHandler) CreateChecklist(ctx *gin.Context, params CreateChecklistParams) {
	var request CreateChecklistRequestObject

	request.Params = params

	var body CreateChecklistJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		ctx.Status(http.StatusBadRequest)
		ctx.Error(err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.CreateChecklist(ctx, request.(CreateChecklistRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateChecklist")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(CreateChecklistResponseObject); ok {
		if err := validResponse.VisitCreateChecklistResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeleteChecklistById operation middleware
func (sh *strictHandler) DeleteChecklistById(ctx *gin.Context, checklistId uint, params DeleteChecklistByIdParams) {
	var request DeleteChecklistByIdRequestObject

	request.ChecklistId = checklistId
	request.Params = params

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteChecklistById(ctx, request.(DeleteChecklistByIdRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteChecklistById")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(DeleteChecklistByIdResponseObject); ok {
		if err := validResponse.VisitDeleteChecklistByIdResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetChecklistById operation middleware
func (sh *strictHandler) GetChecklistById(ctx *gin.Context, checklistId uint, params GetChecklistByIdParams) {
	var request GetChecklistByIdRequestObject

	request.ChecklistId = checklistId
	request.Params = params

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetChecklistById(ctx, request.(GetChecklistByIdRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetChecklistById")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(GetChecklistByIdResponseObject); ok {
		if err := validResponse.VisitGetChecklistByIdResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// UpdateChecklistById operation middleware
func (sh *strictHandler) UpdateChecklistById(ctx *gin.Context, checklistId uint, params UpdateChecklistByIdParams) {
	var request UpdateChecklistByIdRequestObject

	request.ChecklistId = checklistId
	request.Params = params

	var body UpdateChecklistByIdJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		ctx.Status(http.StatusBadRequest)
		ctx.Error(err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.UpdateChecklistById(ctx, request.(UpdateChecklistByIdRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UpdateChecklistById")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(UpdateChecklistByIdResponseObject); ok {
		if err := validResponse.VisitUpdateChecklistByIdResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}
