// Package template provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package template

import (
	"context"
	"encoding/json"
	"fmt"
	"net/http"
	"time"

	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
	strictgin "github.com/oapi-codegen/runtime/strictmiddleware/gin"
)

const (
	CookieAuthScopes = "CookieAuth.Scopes"
)

// ChecklistItemResponse defines model for ChecklistItemResponse.
type ChecklistItemResponse struct {
	Completed   bool                       `json:"completed"`
	Id          uint                       `json:"id"`
	Name        string                     `json:"name"`
	OrderNumber uint                       `json:"orderNumber"`
	Rows        []ChecklistItemRowResponse `json:"rows"`
}

// ChecklistItemRowResponse defines model for ChecklistItemRowResponse.
type ChecklistItemRowResponse struct {
	Completed *bool  `json:"completed"`
	Id        uint   `json:"id"`
	Name      string `json:"name"`
}

// ClaimTemplateInviteResponse defines model for ClaimTemplateInviteResponse.
type ClaimTemplateInviteResponse struct {
	Message    *string `json:"message,omitempty"`
	TemplateId uint    `json:"templateId"`
}

// CreateInviteRequest defines model for CreateInviteRequest.
type CreateInviteRequest struct {
	// ExpiresInHours Hours until invite expires (null = never expires)
	ExpiresInHours *int `json:"expiresInHours"`

	// IsSingleUse If true, invite can only be claimed once
	IsSingleUse bool `json:"isSingleUse"`

	// Name Optional friendly name for the invite (e.g., "For John", "Team members")
	Name *string `json:"name"`
}

// CreateTemplateFromItemRequest defines model for CreateTemplateFromItemRequest.
type CreateTemplateFromItemRequest struct {
	// ChecklistId The checklist to copy the item from
	ChecklistId uint `json:"checklistId"`

	// ChecklistItemId The checklist item to copy into the template
	ChecklistItemId uint    `json:"checklistItemId"`
	Description     *string `json:"description"`
	Name            string  `json:"name"`
}

// CreateTemplateRequest defines model for CreateTemplateRequest.
type CreateTemplateRequest struct {
	Description *string                     `json:"description"`
	Name        string                      `json:"name"`
	Rows        *[]CreateTemplateRowRequest `json:"rows,omitempty"`
}

// CreateTemplateRowRequest defines model for CreateTemplateRowRequest.
type CreateTemplateRowRequest struct {
	Name     string  `json:"name"`
	Position float64 `json:"position"`
}

// Error defines model for Error.
type Error struct {
	Message string `json:"message"`
}

// TemplateInviteResponse defines model for TemplateInviteResponse.
type TemplateInviteResponse struct {
	ClaimedAt *time.Time `json:"claimedAt"`

	// ClaimedBy User ID who claimed (for backend use only, don't display)
	ClaimedBy   *string    `json:"claimedBy"`
	CreatedAt   time.Time  `json:"createdAt"`
	ExpiresAt   *time.Time `json:"expiresAt"`
	Id          uint       `json:"id"`
	InviteToken string     `json:"inviteToken"`

	// InviteUrl Full URL for sharing
	InviteUrl string `json:"inviteUrl"`

	// IsClaimed Computed field indicating if invite is claimed
	IsClaimed bool `json:"isClaimed"`

	// IsExpired Computed field indicating if invite is expired
	IsExpired   bool `json:"isExpired"`
	IsSingleUse bool `json:"isSingleUse"`

	// Name Optional friendly name for the invite
	Name       *string `json:"name"`
	TemplateId uint    `json:"templateId"`
}

// TemplateResponse defines model for TemplateResponse.
type TemplateResponse struct {
	CreatedAt   time.Time `json:"createdAt"`
	Description *string   `json:"description"`
	Id          uint      `json:"id"`

	// IsOwner True if the current user owns this template, false if shared
	IsOwner   bool                  `json:"isOwner"`
	Name      string                `json:"name"`
	Rows      []TemplateRowResponse `json:"rows"`
	UpdatedAt time.Time             `json:"updatedAt"`
	UserId    string                `json:"userId"`
}

// TemplateRowResponse defines model for TemplateRowResponse.
type TemplateRowResponse struct {
	CreatedAt  time.Time `json:"createdAt"`
	Id         uint      `json:"id"`
	Name       string    `json:"name"`
	Position   float64   `json:"position"`
	TemplateId uint      `json:"templateId"`
	UpdatedAt  time.Time `json:"updatedAt"`
}

// XClientId defines model for X-Client-Id.
type XClientId = string

// ApplyTemplateParams defines parameters for ApplyTemplate.
type ApplyTemplateParams struct {
	// XClientId Client identifier sent by frontend in headers
	XClientId *XClientId `json:"X-Client-Id,omitempty"`
}

// ClaimTemplateInviteParams defines parameters for ClaimTemplateInvite.
type ClaimTemplateInviteParams struct {
	// XClientId Client identifier sent by frontend in headers
	XClientId *XClientId `json:"X-Client-Id,omitempty"`
}

// GetAllTemplatesParams defines parameters for GetAllTemplates.
type GetAllTemplatesParams struct {
	// XClientId Client identifier sent by frontend in headers
	XClientId *XClientId `json:"X-Client-Id,omitempty"`
}

// CreateTemplateParams defines parameters for CreateTemplate.
type CreateTemplateParams struct {
	// XClientId Client identifier sent by frontend in headers
	XClientId *XClientId `json:"X-Client-Id,omitempty"`
}

// CreateTemplateFromItemParams defines parameters for CreateTemplateFromItem.
type CreateTemplateFromItemParams struct {
	// XClientId Client identifier sent by frontend in headers
	XClientId *XClientId `json:"X-Client-Id,omitempty"`
}

// RevokeTemplateInviteParams defines parameters for RevokeTemplateInvite.
type RevokeTemplateInviteParams struct {
	// XClientId Client identifier sent by frontend in headers
	XClientId *XClientId `json:"X-Client-Id,omitempty"`
}

// DeleteTemplateParams defines parameters for DeleteTemplate.
type DeleteTemplateParams struct {
	// XClientId Client identifier sent by frontend in headers
	XClientId *XClientId `json:"X-Client-Id,omitempty"`
}

// GetTemplateByIdParams defines parameters for GetTemplateById.
type GetTemplateByIdParams struct {
	// XClientId Client identifier sent by frontend in headers
	XClientId *XClientId `json:"X-Client-Id,omitempty"`
}

// UpdateTemplateParams defines parameters for UpdateTemplate.
type UpdateTemplateParams struct {
	// XClientId Client identifier sent by frontend in headers
	XClientId *XClientId `json:"X-Client-Id,omitempty"`
}

// GetTemplateInvitesParams defines parameters for GetTemplateInvites.
type GetTemplateInvitesParams struct {
	// XClientId Client identifier sent by frontend in headers
	XClientId *XClientId `json:"X-Client-Id,omitempty"`
}

// CreateTemplateInviteParams defines parameters for CreateTemplateInvite.
type CreateTemplateInviteParams struct {
	// XClientId Client identifier sent by frontend in headers
	XClientId *XClientId `json:"X-Client-Id,omitempty"`
}

// LeaveSharedTemplateParams defines parameters for LeaveSharedTemplate.
type LeaveSharedTemplateParams struct {
	// XClientId Client identifier sent by frontend in headers
	XClientId *XClientId `json:"X-Client-Id,omitempty"`
}

// CreateTemplateJSONRequestBody defines body for CreateTemplate for application/json ContentType.
type CreateTemplateJSONRequestBody = CreateTemplateRequest

// CreateTemplateFromItemJSONRequestBody defines body for CreateTemplateFromItem for application/json ContentType.
type CreateTemplateFromItemJSONRequestBody = CreateTemplateFromItemRequest

// UpdateTemplateJSONRequestBody defines body for UpdateTemplate for application/json ContentType.
type UpdateTemplateJSONRequestBody = CreateTemplateRequest

// CreateTemplateInviteJSONRequestBody defines body for CreateTemplateInvite for application/json ContentType.
type CreateTemplateInviteJSONRequestBody = CreateInviteRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Apply template to checklist (creates one checklist item with rows)
	// (POST /api/v1/checklists/{checklistId}/apply-template/{templateId})
	ApplyTemplate(c *gin.Context, checklistId uint, templateId uint, params ApplyTemplateParams)
	// Claim a template invite to gain access to a template
	// (POST /api/v1/template-invites/{token}/claim)
	ClaimTemplateInvite(c *gin.Context, token string, params ClaimTemplateInviteParams)
	// List all templates
	// (GET /api/v1/templates)
	GetAllTemplates(c *gin.Context, params GetAllTemplatesParams)
	// Create a new template
	// (POST /api/v1/templates)
	CreateTemplate(c *gin.Context, params CreateTemplateParams)
	// Create template from existing checklist item
	// (POST /api/v1/templates/from-items)
	CreateTemplateFromItem(c *gin.Context, params CreateTemplateFromItemParams)
	// Revoke a template invite link
	// (DELETE /api/v1/templates/invites/{inviteId})
	RevokeTemplateInvite(c *gin.Context, inviteId uint, params RevokeTemplateInviteParams)
	// Delete template
	// (DELETE /api/v1/templates/{templateId})
	DeleteTemplate(c *gin.Context, templateId uint, params DeleteTemplateParams)
	// Get template by ID
	// (GET /api/v1/templates/{templateId})
	GetTemplateById(c *gin.Context, templateId uint, params GetTemplateByIdParams)
	// Update template
	// (PUT /api/v1/templates/{templateId})
	UpdateTemplate(c *gin.Context, templateId uint, params UpdateTemplateParams)
	// List active invite links for a template
	// (GET /api/v1/templates/{templateId}/invites)
	GetTemplateInvites(c *gin.Context, templateId uint, params GetTemplateInvitesParams)
	// Create a new invite link for a template
	// (POST /api/v1/templates/{templateId}/invites)
	CreateTemplateInvite(c *gin.Context, templateId uint, params CreateTemplateInviteParams)
	// Leave a shared template
	// (POST /api/v1/templates/{templateId}/leave)
	LeaveSharedTemplate(c *gin.Context, templateId uint, params LeaveSharedTemplateParams)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// ApplyTemplate operation middleware
func (siw *ServerInterfaceWrapper) ApplyTemplate(c *gin.Context) {

	var err error

	// ------------- Path parameter "checklistId" -------------
	var checklistId uint

	err = runtime.BindStyledParameterWithOptions("simple", "checklistId", c.Param("checklistId"), &checklistId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter checklistId: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Path parameter "templateId" -------------
	var templateId uint

	err = runtime.BindStyledParameterWithOptions("simple", "templateId", c.Param("templateId"), &templateId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter templateId: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(CookieAuthScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params ApplyTemplateParams

	headers := c.Request.Header

	// ------------- Optional header parameter "X-Client-Id" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Client-Id")]; found {
		var XClientId XClientId
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandler(c, fmt.Errorf("Expected one value for X-Client-Id, got %d", n), http.StatusBadRequest)
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Client-Id", valueList[0], &XClientId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false})
		if err != nil {
			siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter X-Client-Id: %w", err), http.StatusBadRequest)
			return
		}

		params.XClientId = &XClientId

	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ApplyTemplate(c, checklistId, templateId, params)
}

// ClaimTemplateInvite operation middleware
func (siw *ServerInterfaceWrapper) ClaimTemplateInvite(c *gin.Context) {

	var err error

	// ------------- Path parameter "token" -------------
	var token string

	err = runtime.BindStyledParameterWithOptions("simple", "token", c.Param("token"), &token, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter token: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(CookieAuthScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params ClaimTemplateInviteParams

	headers := c.Request.Header

	// ------------- Optional header parameter "X-Client-Id" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Client-Id")]; found {
		var XClientId XClientId
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandler(c, fmt.Errorf("Expected one value for X-Client-Id, got %d", n), http.StatusBadRequest)
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Client-Id", valueList[0], &XClientId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false})
		if err != nil {
			siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter X-Client-Id: %w", err), http.StatusBadRequest)
			return
		}

		params.XClientId = &XClientId

	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ClaimTemplateInvite(c, token, params)
}

// GetAllTemplates operation middleware
func (siw *ServerInterfaceWrapper) GetAllTemplates(c *gin.Context) {

	var err error

	c.Set(CookieAuthScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params GetAllTemplatesParams

	headers := c.Request.Header

	// ------------- Optional header parameter "X-Client-Id" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Client-Id")]; found {
		var XClientId XClientId
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandler(c, fmt.Errorf("Expected one value for X-Client-Id, got %d", n), http.StatusBadRequest)
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Client-Id", valueList[0], &XClientId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false})
		if err != nil {
			siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter X-Client-Id: %w", err), http.StatusBadRequest)
			return
		}

		params.XClientId = &XClientId

	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetAllTemplates(c, params)
}

// CreateTemplate operation middleware
func (siw *ServerInterfaceWrapper) CreateTemplate(c *gin.Context) {

	var err error

	c.Set(CookieAuthScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params CreateTemplateParams

	headers := c.Request.Header

	// ------------- Optional header parameter "X-Client-Id" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Client-Id")]; found {
		var XClientId XClientId
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandler(c, fmt.Errorf("Expected one value for X-Client-Id, got %d", n), http.StatusBadRequest)
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Client-Id", valueList[0], &XClientId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false})
		if err != nil {
			siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter X-Client-Id: %w", err), http.StatusBadRequest)
			return
		}

		params.XClientId = &XClientId

	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateTemplate(c, params)
}

// CreateTemplateFromItem operation middleware
func (siw *ServerInterfaceWrapper) CreateTemplateFromItem(c *gin.Context) {

	var err error

	c.Set(CookieAuthScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params CreateTemplateFromItemParams

	headers := c.Request.Header

	// ------------- Optional header parameter "X-Client-Id" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Client-Id")]; found {
		var XClientId XClientId
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandler(c, fmt.Errorf("Expected one value for X-Client-Id, got %d", n), http.StatusBadRequest)
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Client-Id", valueList[0], &XClientId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false})
		if err != nil {
			siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter X-Client-Id: %w", err), http.StatusBadRequest)
			return
		}

		params.XClientId = &XClientId

	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateTemplateFromItem(c, params)
}

// RevokeTemplateInvite operation middleware
func (siw *ServerInterfaceWrapper) RevokeTemplateInvite(c *gin.Context) {

	var err error

	// ------------- Path parameter "inviteId" -------------
	var inviteId uint

	err = runtime.BindStyledParameterWithOptions("simple", "inviteId", c.Param("inviteId"), &inviteId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter inviteId: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(CookieAuthScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params RevokeTemplateInviteParams

	headers := c.Request.Header

	// ------------- Optional header parameter "X-Client-Id" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Client-Id")]; found {
		var XClientId XClientId
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandler(c, fmt.Errorf("Expected one value for X-Client-Id, got %d", n), http.StatusBadRequest)
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Client-Id", valueList[0], &XClientId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false})
		if err != nil {
			siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter X-Client-Id: %w", err), http.StatusBadRequest)
			return
		}

		params.XClientId = &XClientId

	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.RevokeTemplateInvite(c, inviteId, params)
}

// DeleteTemplate operation middleware
func (siw *ServerInterfaceWrapper) DeleteTemplate(c *gin.Context) {

	var err error

	// ------------- Path parameter "templateId" -------------
	var templateId uint

	err = runtime.BindStyledParameterWithOptions("simple", "templateId", c.Param("templateId"), &templateId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter templateId: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(CookieAuthScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params DeleteTemplateParams

	headers := c.Request.Header

	// ------------- Optional header parameter "X-Client-Id" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Client-Id")]; found {
		var XClientId XClientId
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandler(c, fmt.Errorf("Expected one value for X-Client-Id, got %d", n), http.StatusBadRequest)
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Client-Id", valueList[0], &XClientId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false})
		if err != nil {
			siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter X-Client-Id: %w", err), http.StatusBadRequest)
			return
		}

		params.XClientId = &XClientId

	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DeleteTemplate(c, templateId, params)
}

// GetTemplateById operation middleware
func (siw *ServerInterfaceWrapper) GetTemplateById(c *gin.Context) {

	var err error

	// ------------- Path parameter "templateId" -------------
	var templateId uint

	err = runtime.BindStyledParameterWithOptions("simple", "templateId", c.Param("templateId"), &templateId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter templateId: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(CookieAuthScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params GetTemplateByIdParams

	headers := c.Request.Header

	// ------------- Optional header parameter "X-Client-Id" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Client-Id")]; found {
		var XClientId XClientId
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandler(c, fmt.Errorf("Expected one value for X-Client-Id, got %d", n), http.StatusBadRequest)
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Client-Id", valueList[0], &XClientId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false})
		if err != nil {
			siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter X-Client-Id: %w", err), http.StatusBadRequest)
			return
		}

		params.XClientId = &XClientId

	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetTemplateById(c, templateId, params)
}

// UpdateTemplate operation middleware
func (siw *ServerInterfaceWrapper) UpdateTemplate(c *gin.Context) {

	var err error

	// ------------- Path parameter "templateId" -------------
	var templateId uint

	err = runtime.BindStyledParameterWithOptions("simple", "templateId", c.Param("templateId"), &templateId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter templateId: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(CookieAuthScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params UpdateTemplateParams

	headers := c.Request.Header

	// ------------- Optional header parameter "X-Client-Id" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Client-Id")]; found {
		var XClientId XClientId
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandler(c, fmt.Errorf("Expected one value for X-Client-Id, got %d", n), http.StatusBadRequest)
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Client-Id", valueList[0], &XClientId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false})
		if err != nil {
			siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter X-Client-Id: %w", err), http.StatusBadRequest)
			return
		}

		params.XClientId = &XClientId

	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.UpdateTemplate(c, templateId, params)
}

// GetTemplateInvites operation middleware
func (siw *ServerInterfaceWrapper) GetTemplateInvites(c *gin.Context) {

	var err error

	// ------------- Path parameter "templateId" -------------
	var templateId uint

	err = runtime.BindStyledParameterWithOptions("simple", "templateId", c.Param("templateId"), &templateId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter templateId: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(CookieAuthScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params GetTemplateInvitesParams

	headers := c.Request.Header

	// ------------- Optional header parameter "X-Client-Id" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Client-Id")]; found {
		var XClientId XClientId
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandler(c, fmt.Errorf("Expected one value for X-Client-Id, got %d", n), http.StatusBadRequest)
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Client-Id", valueList[0], &XClientId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false})
		if err != nil {
			siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter X-Client-Id: %w", err), http.StatusBadRequest)
			return
		}

		params.XClientId = &XClientId

	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetTemplateInvites(c, templateId, params)
}

// CreateTemplateInvite operation middleware
func (siw *ServerInterfaceWrapper) CreateTemplateInvite(c *gin.Context) {

	var err error

	// ------------- Path parameter "templateId" -------------
	var templateId uint

	err = runtime.BindStyledParameterWithOptions("simple", "templateId", c.Param("templateId"), &templateId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter templateId: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(CookieAuthScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params CreateTemplateInviteParams

	headers := c.Request.Header

	// ------------- Optional header parameter "X-Client-Id" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Client-Id")]; found {
		var XClientId XClientId
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandler(c, fmt.Errorf("Expected one value for X-Client-Id, got %d", n), http.StatusBadRequest)
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Client-Id", valueList[0], &XClientId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false})
		if err != nil {
			siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter X-Client-Id: %w", err), http.StatusBadRequest)
			return
		}

		params.XClientId = &XClientId

	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateTemplateInvite(c, templateId, params)
}

// LeaveSharedTemplate operation middleware
func (siw *ServerInterfaceWrapper) LeaveSharedTemplate(c *gin.Context) {

	var err error

	// ------------- Path parameter "templateId" -------------
	var templateId uint

	err = runtime.BindStyledParameterWithOptions("simple", "templateId", c.Param("templateId"), &templateId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter templateId: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(CookieAuthScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params LeaveSharedTemplateParams

	headers := c.Request.Header

	// ------------- Optional header parameter "X-Client-Id" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Client-Id")]; found {
		var XClientId XClientId
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandler(c, fmt.Errorf("Expected one value for X-Client-Id, got %d", n), http.StatusBadRequest)
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Client-Id", valueList[0], &XClientId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false})
		if err != nil {
			siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter X-Client-Id: %w", err), http.StatusBadRequest)
			return
		}

		params.XClientId = &XClientId

	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.LeaveSharedTemplate(c, templateId, params)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.POST(options.BaseURL+"/api/v1/checklists/:checklistId/apply-template/:templateId", wrapper.ApplyTemplate)
	router.POST(options.BaseURL+"/api/v1/template-invites/:token/claim", wrapper.ClaimTemplateInvite)
	router.GET(options.BaseURL+"/api/v1/templates", wrapper.GetAllTemplates)
	router.POST(options.BaseURL+"/api/v1/templates", wrapper.CreateTemplate)
	router.POST(options.BaseURL+"/api/v1/templates/from-items", wrapper.CreateTemplateFromItem)
	router.DELETE(options.BaseURL+"/api/v1/templates/invites/:inviteId", wrapper.RevokeTemplateInvite)
	router.DELETE(options.BaseURL+"/api/v1/templates/:templateId", wrapper.DeleteTemplate)
	router.GET(options.BaseURL+"/api/v1/templates/:templateId", wrapper.GetTemplateById)
	router.PUT(options.BaseURL+"/api/v1/templates/:templateId", wrapper.UpdateTemplate)
	router.GET(options.BaseURL+"/api/v1/templates/:templateId/invites", wrapper.GetTemplateInvites)
	router.POST(options.BaseURL+"/api/v1/templates/:templateId/invites", wrapper.CreateTemplateInvite)
	router.POST(options.BaseURL+"/api/v1/templates/:templateId/leave", wrapper.LeaveSharedTemplate)
}

type ApplyTemplateRequestObject struct {
	ChecklistId uint `json:"checklistId"`
	TemplateId  uint `json:"templateId"`
	Params      ApplyTemplateParams
}

type ApplyTemplateResponseObject interface {
	VisitApplyTemplateResponse(w http.ResponseWriter) error
}

type ApplyTemplate200JSONResponse ChecklistItemResponse

func (response ApplyTemplate200JSONResponse) VisitApplyTemplateResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type ApplyTemplate400JSONResponse Error

func (response ApplyTemplate400JSONResponse) VisitApplyTemplateResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type ApplyTemplate404JSONResponse Error

func (response ApplyTemplate404JSONResponse) VisitApplyTemplateResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type ApplyTemplate500JSONResponse Error

func (response ApplyTemplate500JSONResponse) VisitApplyTemplateResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type ClaimTemplateInviteRequestObject struct {
	Token  string `json:"token"`
	Params ClaimTemplateInviteParams
}

type ClaimTemplateInviteResponseObject interface {
	VisitClaimTemplateInviteResponse(w http.ResponseWriter) error
}

type ClaimTemplateInvite200JSONResponse ClaimTemplateInviteResponse

func (response ClaimTemplateInvite200JSONResponse) VisitClaimTemplateInviteResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type ClaimTemplateInvite400JSONResponse Error

func (response ClaimTemplateInvite400JSONResponse) VisitClaimTemplateInviteResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type ClaimTemplateInvite401JSONResponse Error

func (response ClaimTemplateInvite401JSONResponse) VisitClaimTemplateInviteResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type ClaimTemplateInvite404JSONResponse Error

func (response ClaimTemplateInvite404JSONResponse) VisitClaimTemplateInviteResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type ClaimTemplateInvite500JSONResponse Error

func (response ClaimTemplateInvite500JSONResponse) VisitClaimTemplateInviteResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetAllTemplatesRequestObject struct {
	Params GetAllTemplatesParams
}

type GetAllTemplatesResponseObject interface {
	VisitGetAllTemplatesResponse(w http.ResponseWriter) error
}

type GetAllTemplates200JSONResponse []TemplateResponse

func (response GetAllTemplates200JSONResponse) VisitGetAllTemplatesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetAllTemplates500JSONResponse Error

func (response GetAllTemplates500JSONResponse) VisitGetAllTemplatesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type CreateTemplateRequestObject struct {
	Params CreateTemplateParams
	Body   *CreateTemplateJSONRequestBody
}

type CreateTemplateResponseObject interface {
	VisitCreateTemplateResponse(w http.ResponseWriter) error
}

type CreateTemplate201JSONResponse TemplateResponse

func (response CreateTemplate201JSONResponse) VisitCreateTemplateResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type CreateTemplate400JSONResponse Error

func (response CreateTemplate400JSONResponse) VisitCreateTemplateResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type CreateTemplate500JSONResponse Error

func (response CreateTemplate500JSONResponse) VisitCreateTemplateResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type CreateTemplateFromItemRequestObject struct {
	Params CreateTemplateFromItemParams
	Body   *CreateTemplateFromItemJSONRequestBody
}

type CreateTemplateFromItemResponseObject interface {
	VisitCreateTemplateFromItemResponse(w http.ResponseWriter) error
}

type CreateTemplateFromItem201JSONResponse TemplateResponse

func (response CreateTemplateFromItem201JSONResponse) VisitCreateTemplateFromItemResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type CreateTemplateFromItem400JSONResponse Error

func (response CreateTemplateFromItem400JSONResponse) VisitCreateTemplateFromItemResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type CreateTemplateFromItem404JSONResponse Error

func (response CreateTemplateFromItem404JSONResponse) VisitCreateTemplateFromItemResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type CreateTemplateFromItem500JSONResponse Error

func (response CreateTemplateFromItem500JSONResponse) VisitCreateTemplateFromItemResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type RevokeTemplateInviteRequestObject struct {
	InviteId uint `json:"inviteId"`
	Params   RevokeTemplateInviteParams
}

type RevokeTemplateInviteResponseObject interface {
	VisitRevokeTemplateInviteResponse(w http.ResponseWriter) error
}

type RevokeTemplateInvite204Response struct {
}

func (response RevokeTemplateInvite204Response) VisitRevokeTemplateInviteResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type RevokeTemplateInvite404JSONResponse Error

func (response RevokeTemplateInvite404JSONResponse) VisitRevokeTemplateInviteResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type RevokeTemplateInvite500JSONResponse Error

func (response RevokeTemplateInvite500JSONResponse) VisitRevokeTemplateInviteResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type DeleteTemplateRequestObject struct {
	TemplateId uint `json:"templateId"`
	Params     DeleteTemplateParams
}

type DeleteTemplateResponseObject interface {
	VisitDeleteTemplateResponse(w http.ResponseWriter) error
}

type DeleteTemplate204Response struct {
}

func (response DeleteTemplate204Response) VisitDeleteTemplateResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type DeleteTemplate404JSONResponse Error

func (response DeleteTemplate404JSONResponse) VisitDeleteTemplateResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type DeleteTemplate500JSONResponse Error

func (response DeleteTemplate500JSONResponse) VisitDeleteTemplateResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetTemplateByIdRequestObject struct {
	TemplateId uint `json:"templateId"`
	Params     GetTemplateByIdParams
}

type GetTemplateByIdResponseObject interface {
	VisitGetTemplateByIdResponse(w http.ResponseWriter) error
}

type GetTemplateById200JSONResponse TemplateResponse

func (response GetTemplateById200JSONResponse) VisitGetTemplateByIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetTemplateById404JSONResponse Error

func (response GetTemplateById404JSONResponse) VisitGetTemplateByIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type GetTemplateById500JSONResponse Error

func (response GetTemplateById500JSONResponse) VisitGetTemplateByIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type UpdateTemplateRequestObject struct {
	TemplateId uint `json:"templateId"`
	Params     UpdateTemplateParams
	Body       *UpdateTemplateJSONRequestBody
}

type UpdateTemplateResponseObject interface {
	VisitUpdateTemplateResponse(w http.ResponseWriter) error
}

type UpdateTemplate200JSONResponse TemplateResponse

func (response UpdateTemplate200JSONResponse) VisitUpdateTemplateResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type UpdateTemplate400JSONResponse Error

func (response UpdateTemplate400JSONResponse) VisitUpdateTemplateResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type UpdateTemplate404JSONResponse Error

func (response UpdateTemplate404JSONResponse) VisitUpdateTemplateResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type UpdateTemplate500JSONResponse Error

func (response UpdateTemplate500JSONResponse) VisitUpdateTemplateResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetTemplateInvitesRequestObject struct {
	TemplateId uint `json:"templateId"`
	Params     GetTemplateInvitesParams
}

type GetTemplateInvitesResponseObject interface {
	VisitGetTemplateInvitesResponse(w http.ResponseWriter) error
}

type GetTemplateInvites200JSONResponse []TemplateInviteResponse

func (response GetTemplateInvites200JSONResponse) VisitGetTemplateInvitesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetTemplateInvites404JSONResponse Error

func (response GetTemplateInvites404JSONResponse) VisitGetTemplateInvitesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type GetTemplateInvites500JSONResponse Error

func (response GetTemplateInvites500JSONResponse) VisitGetTemplateInvitesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type CreateTemplateInviteRequestObject struct {
	TemplateId uint `json:"templateId"`
	Params     CreateTemplateInviteParams
	Body       *CreateTemplateInviteJSONRequestBody
}

type CreateTemplateInviteResponseObject interface {
	VisitCreateTemplateInviteResponse(w http.ResponseWriter) error
}

type CreateTemplateInvite201JSONResponse TemplateInviteResponse

func (response CreateTemplateInvite201JSONResponse) VisitCreateTemplateInviteResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type CreateTemplateInvite404JSONResponse Error

func (response CreateTemplateInvite404JSONResponse) VisitCreateTemplateInviteResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type CreateTemplateInvite500JSONResponse Error

func (response CreateTemplateInvite500JSONResponse) VisitCreateTemplateInviteResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type LeaveSharedTemplateRequestObject struct {
	TemplateId uint `json:"templateId"`
	Params     LeaveSharedTemplateParams
}

type LeaveSharedTemplateResponseObject interface {
	VisitLeaveSharedTemplateResponse(w http.ResponseWriter) error
}

type LeaveSharedTemplate204Response struct {
}

func (response LeaveSharedTemplate204Response) VisitLeaveSharedTemplateResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type LeaveSharedTemplate400JSONResponse Error

func (response LeaveSharedTemplate400JSONResponse) VisitLeaveSharedTemplateResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type LeaveSharedTemplate401JSONResponse Error

func (response LeaveSharedTemplate401JSONResponse) VisitLeaveSharedTemplateResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type LeaveSharedTemplate404JSONResponse Error

func (response LeaveSharedTemplate404JSONResponse) VisitLeaveSharedTemplateResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type LeaveSharedTemplate500JSONResponse Error

func (response LeaveSharedTemplate500JSONResponse) VisitLeaveSharedTemplateResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Apply template to checklist (creates one checklist item with rows)
	// (POST /api/v1/checklists/{checklistId}/apply-template/{templateId})
	ApplyTemplate(ctx context.Context, request ApplyTemplateRequestObject) (ApplyTemplateResponseObject, error)
	// Claim a template invite to gain access to a template
	// (POST /api/v1/template-invites/{token}/claim)
	ClaimTemplateInvite(ctx context.Context, request ClaimTemplateInviteRequestObject) (ClaimTemplateInviteResponseObject, error)
	// List all templates
	// (GET /api/v1/templates)
	GetAllTemplates(ctx context.Context, request GetAllTemplatesRequestObject) (GetAllTemplatesResponseObject, error)
	// Create a new template
	// (POST /api/v1/templates)
	CreateTemplate(ctx context.Context, request CreateTemplateRequestObject) (CreateTemplateResponseObject, error)
	// Create template from existing checklist item
	// (POST /api/v1/templates/from-items)
	CreateTemplateFromItem(ctx context.Context, request CreateTemplateFromItemRequestObject) (CreateTemplateFromItemResponseObject, error)
	// Revoke a template invite link
	// (DELETE /api/v1/templates/invites/{inviteId})
	RevokeTemplateInvite(ctx context.Context, request RevokeTemplateInviteRequestObject) (RevokeTemplateInviteResponseObject, error)
	// Delete template
	// (DELETE /api/v1/templates/{templateId})
	DeleteTemplate(ctx context.Context, request DeleteTemplateRequestObject) (DeleteTemplateResponseObject, error)
	// Get template by ID
	// (GET /api/v1/templates/{templateId})
	GetTemplateById(ctx context.Context, request GetTemplateByIdRequestObject) (GetTemplateByIdResponseObject, error)
	// Update template
	// (PUT /api/v1/templates/{templateId})
	UpdateTemplate(ctx context.Context, request UpdateTemplateRequestObject) (UpdateTemplateResponseObject, error)
	// List active invite links for a template
	// (GET /api/v1/templates/{templateId}/invites)
	GetTemplateInvites(ctx context.Context, request GetTemplateInvitesRequestObject) (GetTemplateInvitesResponseObject, error)
	// Create a new invite link for a template
	// (POST /api/v1/templates/{templateId}/invites)
	CreateTemplateInvite(ctx context.Context, request CreateTemplateInviteRequestObject) (CreateTemplateInviteResponseObject, error)
	// Leave a shared template
	// (POST /api/v1/templates/{templateId}/leave)
	LeaveSharedTemplate(ctx context.Context, request LeaveSharedTemplateRequestObject) (LeaveSharedTemplateResponseObject, error)
}

type StrictHandlerFunc = strictgin.StrictGinHandlerFunc
type StrictMiddlewareFunc = strictgin.StrictGinMiddlewareFunc

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
}

// ApplyTemplate operation middleware
func (sh *strictHandler) ApplyTemplate(ctx *gin.Context, checklistId uint, templateId uint, params ApplyTemplateParams) {
	var request ApplyTemplateRequestObject

	request.ChecklistId = checklistId
	request.TemplateId = templateId
	request.Params = params

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.ApplyTemplate(ctx, request.(ApplyTemplateRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ApplyTemplate")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(ApplyTemplateResponseObject); ok {
		if err := validResponse.VisitApplyTemplateResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// ClaimTemplateInvite operation middleware
func (sh *strictHandler) ClaimTemplateInvite(ctx *gin.Context, token string, params ClaimTemplateInviteParams) {
	var request ClaimTemplateInviteRequestObject

	request.Token = token
	request.Params = params

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.ClaimTemplateInvite(ctx, request.(ClaimTemplateInviteRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ClaimTemplateInvite")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(ClaimTemplateInviteResponseObject); ok {
		if err := validResponse.VisitClaimTemplateInviteResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetAllTemplates operation middleware
func (sh *strictHandler) GetAllTemplates(ctx *gin.Context, params GetAllTemplatesParams) {
	var request GetAllTemplatesRequestObject

	request.Params = params

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetAllTemplates(ctx, request.(GetAllTemplatesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetAllTemplates")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(GetAllTemplatesResponseObject); ok {
		if err := validResponse.VisitGetAllTemplatesResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateTemplate operation middleware
func (sh *strictHandler) CreateTemplate(ctx *gin.Context, params CreateTemplateParams) {
	var request CreateTemplateRequestObject

	request.Params = params

	var body CreateTemplateJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		ctx.Status(http.StatusBadRequest)
		ctx.Error(err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.CreateTemplate(ctx, request.(CreateTemplateRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateTemplate")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(CreateTemplateResponseObject); ok {
		if err := validResponse.VisitCreateTemplateResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateTemplateFromItem operation middleware
func (sh *strictHandler) CreateTemplateFromItem(ctx *gin.Context, params CreateTemplateFromItemParams) {
	var request CreateTemplateFromItemRequestObject

	request.Params = params

	var body CreateTemplateFromItemJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		ctx.Status(http.StatusBadRequest)
		ctx.Error(err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.CreateTemplateFromItem(ctx, request.(CreateTemplateFromItemRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateTemplateFromItem")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(CreateTemplateFromItemResponseObject); ok {
		if err := validResponse.VisitCreateTemplateFromItemResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// RevokeTemplateInvite operation middleware
func (sh *strictHandler) RevokeTemplateInvite(ctx *gin.Context, inviteId uint, params RevokeTemplateInviteParams) {
	var request RevokeTemplateInviteRequestObject

	request.InviteId = inviteId
	request.Params = params

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.RevokeTemplateInvite(ctx, request.(RevokeTemplateInviteRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "RevokeTemplateInvite")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(RevokeTemplateInviteResponseObject); ok {
		if err := validResponse.VisitRevokeTemplateInviteResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeleteTemplate operation middleware
func (sh *strictHandler) DeleteTemplate(ctx *gin.Context, templateId uint, params DeleteTemplateParams) {
	var request DeleteTemplateRequestObject

	request.TemplateId = templateId
	request.Params = params

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteTemplate(ctx, request.(DeleteTemplateRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteTemplate")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(DeleteTemplateResponseObject); ok {
		if err := validResponse.VisitDeleteTemplateResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetTemplateById operation middleware
func (sh *strictHandler) GetTemplateById(ctx *gin.Context, templateId uint, params GetTemplateByIdParams) {
	var request GetTemplateByIdRequestObject

	request.TemplateId = templateId
	request.Params = params

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetTemplateById(ctx, request.(GetTemplateByIdRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetTemplateById")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(GetTemplateByIdResponseObject); ok {
		if err := validResponse.VisitGetTemplateByIdResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// UpdateTemplate operation middleware
func (sh *strictHandler) UpdateTemplate(ctx *gin.Context, templateId uint, params UpdateTemplateParams) {
	var request UpdateTemplateRequestObject

	request.TemplateId = templateId
	request.Params = params

	var body UpdateTemplateJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		ctx.Status(http.StatusBadRequest)
		ctx.Error(err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.UpdateTemplate(ctx, request.(UpdateTemplateRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UpdateTemplate")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(UpdateTemplateResponseObject); ok {
		if err := validResponse.VisitUpdateTemplateResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetTemplateInvites operation middleware
func (sh *strictHandler) GetTemplateInvites(ctx *gin.Context, templateId uint, params GetTemplateInvitesParams) {
	var request GetTemplateInvitesRequestObject

	request.TemplateId = templateId
	request.Params = params

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetTemplateInvites(ctx, request.(GetTemplateInvitesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetTemplateInvites")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(GetTemplateInvitesResponseObject); ok {
		if err := validResponse.VisitGetTemplateInvitesResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateTemplateInvite operation middleware
func (sh *strictHandler) CreateTemplateInvite(ctx *gin.Context, templateId uint, params CreateTemplateInviteParams) {
	var request CreateTemplateInviteRequestObject

	request.TemplateId = templateId
	request.Params = params

	var body CreateTemplateInviteJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		ctx.Status(http.StatusBadRequest)
		ctx.Error(err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.CreateTemplateInvite(ctx, request.(CreateTemplateInviteRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateTemplateInvite")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(CreateTemplateInviteResponseObject); ok {
		if err := validResponse.VisitCreateTemplateInviteResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// LeaveSharedTemplate operation middleware
func (sh *strictHandler) LeaveSharedTemplate(ctx *gin.Context, templateId uint, params LeaveSharedTemplateParams) {
	var request LeaveSharedTemplateRequestObject

	request.TemplateId = templateId
	request.Params = params

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.LeaveSharedTemplate(ctx, request.(LeaveSharedTemplateRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "LeaveSharedTemplate")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(LeaveSharedTemplateResponseObject); ok {
		if err := validResponse.VisitLeaveSharedTemplateResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}
