// Package template provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package template

import (
	"context"
	"encoding/json"
	"fmt"
	"net/http"
	"time"

	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
	strictgin "github.com/oapi-codegen/runtime/strictmiddleware/gin"
)

const (
	CookieAuthScopes = "CookieAuth.Scopes"
)

// ApplyTemplateRequest defines model for ApplyTemplateRequest.
type ApplyTemplateRequest struct {
	// ItemIds Template item IDs to add
	ItemIds []uint `json:"itemIds"`
}

// ChecklistItemResponse defines model for ChecklistItemResponse.
type ChecklistItemResponse struct {
	Completed   bool                       `json:"completed"`
	Id          uint                       `json:"id"`
	Name        string                     `json:"name"`
	OrderNumber uint                       `json:"orderNumber"`
	Rows        []ChecklistItemRowResponse `json:"rows"`
}

// ChecklistItemRowResponse defines model for ChecklistItemRowResponse.
type ChecklistItemRowResponse struct {
	Completed *bool  `json:"completed"`
	Id        uint   `json:"id"`
	Name      string `json:"name"`
}

// ChecklistResponse defines model for ChecklistResponse.
type ChecklistResponse struct {
	Id uint `json:"id"`

	// IsOwner Whether the current user is the owner
	IsOwner bool `json:"isOwner"`

	// IsShared Whether this checklist is shared with others (only true for owners)
	IsShared bool `json:"isShared"`

	// Items Full list of items (only included in detail view)
	Items *[]ChecklistItemResponse `json:"items,omitempty"`
	Name  string                   `json:"name"`

	// Owner User ID of the checklist owner
	Owner string `json:"owner"`

	// SharedWith List of user IDs this checklist is shared with (only included for owners)
	SharedWith *[]string `json:"sharedWith,omitempty"`

	// Stats Statistics about checklist items
	Stats struct {
		// CompletedItems Number of completed items
		CompletedItems uint `json:"completedItems"`

		// TotalItems Total number of items in the checklist
		TotalItems uint `json:"totalItems"`
	} `json:"stats"`
}

// CreateChecklistFromTemplateRequest defines model for CreateChecklistFromTemplateRequest.
type CreateChecklistFromTemplateRequest struct {
	// Name Name for the new checklist
	Name string `json:"name"`
}

// CreateTemplateFromItemsRequest defines model for CreateTemplateFromItemsRequest.
type CreateTemplateFromItemsRequest struct {
	// ChecklistId The checklist to copy items from
	ChecklistId uint `json:"checklistId"`

	// ChecklistItemIds Checklist item IDs to copy into the template
	ChecklistItemIds []uint  `json:"checklistItemIds"`
	Description      *string `json:"description"`
	Name             string  `json:"name"`
}

// CreateTemplateRequest defines model for CreateTemplateRequest.
type CreateTemplateRequest struct {
	Description *string `json:"description"`
	Name        string  `json:"name"`
}

// Error defines model for Error.
type Error struct {
	Message string `json:"message"`
}

// TemplateItemResponse defines model for TemplateItemResponse.
type TemplateItemResponse struct {
	CreatedAt  time.Time `json:"createdAt"`
	Id         uint      `json:"id"`
	Name       string    `json:"name"`
	Position   float64   `json:"position"`
	TemplateId uint      `json:"templateId"`
	UpdatedAt  time.Time `json:"updatedAt"`
}

// TemplatePreviewResponse defines model for TemplatePreviewResponse.
type TemplatePreviewResponse struct {
	// ExistingItems Items already in checklist
	ExistingItems []TemplateItemResponse `json:"existingItems"`

	// NewItems New items from template
	NewItems []TemplateItemResponse `json:"newItems"`
}

// TemplateResponse defines model for TemplateResponse.
type TemplateResponse struct {
	CreatedAt   time.Time              `json:"createdAt"`
	Description *string                `json:"description"`
	Id          uint                   `json:"id"`
	Items       []TemplateItemResponse `json:"items"`
	Name        string                 `json:"name"`
	UpdatedAt   time.Time              `json:"updatedAt"`
	UserId      string                 `json:"userId"`
}

// XClientId defines model for X-Client-Id.
type XClientId = string

// ApplyTemplateParams defines parameters for ApplyTemplate.
type ApplyTemplateParams struct {
	// XClientId Client identifier sent by frontend in headers
	XClientId *XClientId `json:"X-Client-Id,omitempty"`
}

// GetTemplatePreviewParams defines parameters for GetTemplatePreview.
type GetTemplatePreviewParams struct {
	// XClientId Client identifier sent by frontend in headers
	XClientId *XClientId `json:"X-Client-Id,omitempty"`
}

// GetAllTemplatesParams defines parameters for GetAllTemplates.
type GetAllTemplatesParams struct {
	// XClientId Client identifier sent by frontend in headers
	XClientId *XClientId `json:"X-Client-Id,omitempty"`
}

// CreateTemplateParams defines parameters for CreateTemplate.
type CreateTemplateParams struct {
	// XClientId Client identifier sent by frontend in headers
	XClientId *XClientId `json:"X-Client-Id,omitempty"`
}

// CreateTemplateFromItemsParams defines parameters for CreateTemplateFromItems.
type CreateTemplateFromItemsParams struct {
	// XClientId Client identifier sent by frontend in headers
	XClientId *XClientId `json:"X-Client-Id,omitempty"`
}

// DeleteTemplateParams defines parameters for DeleteTemplate.
type DeleteTemplateParams struct {
	// XClientId Client identifier sent by frontend in headers
	XClientId *XClientId `json:"X-Client-Id,omitempty"`
}

// GetTemplateByIdParams defines parameters for GetTemplateById.
type GetTemplateByIdParams struct {
	// XClientId Client identifier sent by frontend in headers
	XClientId *XClientId `json:"X-Client-Id,omitempty"`
}

// UpdateTemplateParams defines parameters for UpdateTemplate.
type UpdateTemplateParams struct {
	// XClientId Client identifier sent by frontend in headers
	XClientId *XClientId `json:"X-Client-Id,omitempty"`
}

// CreateChecklistFromTemplateParams defines parameters for CreateChecklistFromTemplate.
type CreateChecklistFromTemplateParams struct {
	// XClientId Client identifier sent by frontend in headers
	XClientId *XClientId `json:"X-Client-Id,omitempty"`
}

// ApplyTemplateJSONRequestBody defines body for ApplyTemplate for application/json ContentType.
type ApplyTemplateJSONRequestBody = ApplyTemplateRequest

// CreateTemplateJSONRequestBody defines body for CreateTemplate for application/json ContentType.
type CreateTemplateJSONRequestBody = CreateTemplateRequest

// CreateTemplateFromItemsJSONRequestBody defines body for CreateTemplateFromItems for application/json ContentType.
type CreateTemplateFromItemsJSONRequestBody = CreateTemplateFromItemsRequest

// UpdateTemplateJSONRequestBody defines body for UpdateTemplate for application/json ContentType.
type UpdateTemplateJSONRequestBody = CreateTemplateRequest

// CreateChecklistFromTemplateJSONRequestBody defines body for CreateChecklistFromTemplate for application/json ContentType.
type CreateChecklistFromTemplateJSONRequestBody = CreateChecklistFromTemplateRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Apply template to checklist
	// (POST /api/v1/checklists/{checklistId}/apply-template/{templateId})
	ApplyTemplate(c *gin.Context, checklistId uint, templateId uint, params ApplyTemplateParams)
	// Get template preview with duplicate detection
	// (GET /api/v1/checklists/{checklistId}/template-preview/{templateId})
	GetTemplatePreview(c *gin.Context, checklistId uint, templateId uint, params GetTemplatePreviewParams)
	// List all templates
	// (GET /api/v1/templates)
	GetAllTemplates(c *gin.Context, params GetAllTemplatesParams)
	// Create a new template
	// (POST /api/v1/templates)
	CreateTemplate(c *gin.Context, params CreateTemplateParams)
	// Create template from existing checklist items
	// (POST /api/v1/templates/from-items)
	CreateTemplateFromItems(c *gin.Context, params CreateTemplateFromItemsParams)
	// Delete template
	// (DELETE /api/v1/templates/{templateId})
	DeleteTemplate(c *gin.Context, templateId uint, params DeleteTemplateParams)
	// Get template by ID
	// (GET /api/v1/templates/{templateId})
	GetTemplateById(c *gin.Context, templateId uint, params GetTemplateByIdParams)
	// Update template
	// (PUT /api/v1/templates/{templateId})
	UpdateTemplate(c *gin.Context, templateId uint, params UpdateTemplateParams)
	// Create a new checklist pre-populated with all template items
	// (POST /api/v1/templates/{templateId}/create-checklist)
	CreateChecklistFromTemplate(c *gin.Context, templateId uint, params CreateChecklistFromTemplateParams)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// ApplyTemplate operation middleware
func (siw *ServerInterfaceWrapper) ApplyTemplate(c *gin.Context) {

	var err error

	// ------------- Path parameter "checklistId" -------------
	var checklistId uint

	err = runtime.BindStyledParameterWithOptions("simple", "checklistId", c.Param("checklistId"), &checklistId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter checklistId: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Path parameter "templateId" -------------
	var templateId uint

	err = runtime.BindStyledParameterWithOptions("simple", "templateId", c.Param("templateId"), &templateId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter templateId: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(CookieAuthScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params ApplyTemplateParams

	headers := c.Request.Header

	// ------------- Optional header parameter "X-Client-Id" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Client-Id")]; found {
		var XClientId XClientId
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandler(c, fmt.Errorf("Expected one value for X-Client-Id, got %d", n), http.StatusBadRequest)
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Client-Id", valueList[0], &XClientId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false})
		if err != nil {
			siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter X-Client-Id: %w", err), http.StatusBadRequest)
			return
		}

		params.XClientId = &XClientId

	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ApplyTemplate(c, checklistId, templateId, params)
}

// GetTemplatePreview operation middleware
func (siw *ServerInterfaceWrapper) GetTemplatePreview(c *gin.Context) {

	var err error

	// ------------- Path parameter "checklistId" -------------
	var checklistId uint

	err = runtime.BindStyledParameterWithOptions("simple", "checklistId", c.Param("checklistId"), &checklistId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter checklistId: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Path parameter "templateId" -------------
	var templateId uint

	err = runtime.BindStyledParameterWithOptions("simple", "templateId", c.Param("templateId"), &templateId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter templateId: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(CookieAuthScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params GetTemplatePreviewParams

	headers := c.Request.Header

	// ------------- Optional header parameter "X-Client-Id" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Client-Id")]; found {
		var XClientId XClientId
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandler(c, fmt.Errorf("Expected one value for X-Client-Id, got %d", n), http.StatusBadRequest)
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Client-Id", valueList[0], &XClientId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false})
		if err != nil {
			siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter X-Client-Id: %w", err), http.StatusBadRequest)
			return
		}

		params.XClientId = &XClientId

	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetTemplatePreview(c, checklistId, templateId, params)
}

// GetAllTemplates operation middleware
func (siw *ServerInterfaceWrapper) GetAllTemplates(c *gin.Context) {

	var err error

	c.Set(CookieAuthScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params GetAllTemplatesParams

	headers := c.Request.Header

	// ------------- Optional header parameter "X-Client-Id" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Client-Id")]; found {
		var XClientId XClientId
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandler(c, fmt.Errorf("Expected one value for X-Client-Id, got %d", n), http.StatusBadRequest)
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Client-Id", valueList[0], &XClientId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false})
		if err != nil {
			siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter X-Client-Id: %w", err), http.StatusBadRequest)
			return
		}

		params.XClientId = &XClientId

	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetAllTemplates(c, params)
}

// CreateTemplate operation middleware
func (siw *ServerInterfaceWrapper) CreateTemplate(c *gin.Context) {

	var err error

	c.Set(CookieAuthScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params CreateTemplateParams

	headers := c.Request.Header

	// ------------- Optional header parameter "X-Client-Id" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Client-Id")]; found {
		var XClientId XClientId
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandler(c, fmt.Errorf("Expected one value for X-Client-Id, got %d", n), http.StatusBadRequest)
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Client-Id", valueList[0], &XClientId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false})
		if err != nil {
			siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter X-Client-Id: %w", err), http.StatusBadRequest)
			return
		}

		params.XClientId = &XClientId

	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateTemplate(c, params)
}

// CreateTemplateFromItems operation middleware
func (siw *ServerInterfaceWrapper) CreateTemplateFromItems(c *gin.Context) {

	var err error

	c.Set(CookieAuthScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params CreateTemplateFromItemsParams

	headers := c.Request.Header

	// ------------- Optional header parameter "X-Client-Id" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Client-Id")]; found {
		var XClientId XClientId
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandler(c, fmt.Errorf("Expected one value for X-Client-Id, got %d", n), http.StatusBadRequest)
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Client-Id", valueList[0], &XClientId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false})
		if err != nil {
			siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter X-Client-Id: %w", err), http.StatusBadRequest)
			return
		}

		params.XClientId = &XClientId

	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateTemplateFromItems(c, params)
}

// DeleteTemplate operation middleware
func (siw *ServerInterfaceWrapper) DeleteTemplate(c *gin.Context) {

	var err error

	// ------------- Path parameter "templateId" -------------
	var templateId uint

	err = runtime.BindStyledParameterWithOptions("simple", "templateId", c.Param("templateId"), &templateId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter templateId: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(CookieAuthScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params DeleteTemplateParams

	headers := c.Request.Header

	// ------------- Optional header parameter "X-Client-Id" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Client-Id")]; found {
		var XClientId XClientId
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandler(c, fmt.Errorf("Expected one value for X-Client-Id, got %d", n), http.StatusBadRequest)
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Client-Id", valueList[0], &XClientId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false})
		if err != nil {
			siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter X-Client-Id: %w", err), http.StatusBadRequest)
			return
		}

		params.XClientId = &XClientId

	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DeleteTemplate(c, templateId, params)
}

// GetTemplateById operation middleware
func (siw *ServerInterfaceWrapper) GetTemplateById(c *gin.Context) {

	var err error

	// ------------- Path parameter "templateId" -------------
	var templateId uint

	err = runtime.BindStyledParameterWithOptions("simple", "templateId", c.Param("templateId"), &templateId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter templateId: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(CookieAuthScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params GetTemplateByIdParams

	headers := c.Request.Header

	// ------------- Optional header parameter "X-Client-Id" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Client-Id")]; found {
		var XClientId XClientId
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandler(c, fmt.Errorf("Expected one value for X-Client-Id, got %d", n), http.StatusBadRequest)
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Client-Id", valueList[0], &XClientId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false})
		if err != nil {
			siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter X-Client-Id: %w", err), http.StatusBadRequest)
			return
		}

		params.XClientId = &XClientId

	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetTemplateById(c, templateId, params)
}

// UpdateTemplate operation middleware
func (siw *ServerInterfaceWrapper) UpdateTemplate(c *gin.Context) {

	var err error

	// ------------- Path parameter "templateId" -------------
	var templateId uint

	err = runtime.BindStyledParameterWithOptions("simple", "templateId", c.Param("templateId"), &templateId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter templateId: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(CookieAuthScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params UpdateTemplateParams

	headers := c.Request.Header

	// ------------- Optional header parameter "X-Client-Id" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Client-Id")]; found {
		var XClientId XClientId
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandler(c, fmt.Errorf("Expected one value for X-Client-Id, got %d", n), http.StatusBadRequest)
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Client-Id", valueList[0], &XClientId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false})
		if err != nil {
			siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter X-Client-Id: %w", err), http.StatusBadRequest)
			return
		}

		params.XClientId = &XClientId

	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.UpdateTemplate(c, templateId, params)
}

// CreateChecklistFromTemplate operation middleware
func (siw *ServerInterfaceWrapper) CreateChecklistFromTemplate(c *gin.Context) {

	var err error

	// ------------- Path parameter "templateId" -------------
	var templateId uint

	err = runtime.BindStyledParameterWithOptions("simple", "templateId", c.Param("templateId"), &templateId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter templateId: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(CookieAuthScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params CreateChecklistFromTemplateParams

	headers := c.Request.Header

	// ------------- Optional header parameter "X-Client-Id" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Client-Id")]; found {
		var XClientId XClientId
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandler(c, fmt.Errorf("Expected one value for X-Client-Id, got %d", n), http.StatusBadRequest)
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Client-Id", valueList[0], &XClientId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false})
		if err != nil {
			siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter X-Client-Id: %w", err), http.StatusBadRequest)
			return
		}

		params.XClientId = &XClientId

	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateChecklistFromTemplate(c, templateId, params)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.POST(options.BaseURL+"/api/v1/checklists/:checklistId/apply-template/:templateId", wrapper.ApplyTemplate)
	router.GET(options.BaseURL+"/api/v1/checklists/:checklistId/template-preview/:templateId", wrapper.GetTemplatePreview)
	router.GET(options.BaseURL+"/api/v1/templates", wrapper.GetAllTemplates)
	router.POST(options.BaseURL+"/api/v1/templates", wrapper.CreateTemplate)
	router.POST(options.BaseURL+"/api/v1/templates/from-items", wrapper.CreateTemplateFromItems)
	router.DELETE(options.BaseURL+"/api/v1/templates/:templateId", wrapper.DeleteTemplate)
	router.GET(options.BaseURL+"/api/v1/templates/:templateId", wrapper.GetTemplateById)
	router.PUT(options.BaseURL+"/api/v1/templates/:templateId", wrapper.UpdateTemplate)
	router.POST(options.BaseURL+"/api/v1/templates/:templateId/create-checklist", wrapper.CreateChecklistFromTemplate)
}

type ApplyTemplateRequestObject struct {
	ChecklistId uint `json:"checklistId"`
	TemplateId  uint `json:"templateId"`
	Params      ApplyTemplateParams
	Body        *ApplyTemplateJSONRequestBody
}

type ApplyTemplateResponseObject interface {
	VisitApplyTemplateResponse(w http.ResponseWriter) error
}

type ApplyTemplate200JSONResponse []ChecklistItemResponse

func (response ApplyTemplate200JSONResponse) VisitApplyTemplateResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type ApplyTemplate400JSONResponse Error

func (response ApplyTemplate400JSONResponse) VisitApplyTemplateResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type ApplyTemplate404JSONResponse Error

func (response ApplyTemplate404JSONResponse) VisitApplyTemplateResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type ApplyTemplate500JSONResponse Error

func (response ApplyTemplate500JSONResponse) VisitApplyTemplateResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetTemplatePreviewRequestObject struct {
	ChecklistId uint `json:"checklistId"`
	TemplateId  uint `json:"templateId"`
	Params      GetTemplatePreviewParams
}

type GetTemplatePreviewResponseObject interface {
	VisitGetTemplatePreviewResponse(w http.ResponseWriter) error
}

type GetTemplatePreview200JSONResponse TemplatePreviewResponse

func (response GetTemplatePreview200JSONResponse) VisitGetTemplatePreviewResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetTemplatePreview404JSONResponse Error

func (response GetTemplatePreview404JSONResponse) VisitGetTemplatePreviewResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type GetTemplatePreview500JSONResponse Error

func (response GetTemplatePreview500JSONResponse) VisitGetTemplatePreviewResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetAllTemplatesRequestObject struct {
	Params GetAllTemplatesParams
}

type GetAllTemplatesResponseObject interface {
	VisitGetAllTemplatesResponse(w http.ResponseWriter) error
}

type GetAllTemplates200JSONResponse []TemplateResponse

func (response GetAllTemplates200JSONResponse) VisitGetAllTemplatesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetAllTemplates500JSONResponse Error

func (response GetAllTemplates500JSONResponse) VisitGetAllTemplatesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type CreateTemplateRequestObject struct {
	Params CreateTemplateParams
	Body   *CreateTemplateJSONRequestBody
}

type CreateTemplateResponseObject interface {
	VisitCreateTemplateResponse(w http.ResponseWriter) error
}

type CreateTemplate201JSONResponse TemplateResponse

func (response CreateTemplate201JSONResponse) VisitCreateTemplateResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type CreateTemplate400JSONResponse Error

func (response CreateTemplate400JSONResponse) VisitCreateTemplateResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type CreateTemplate500JSONResponse Error

func (response CreateTemplate500JSONResponse) VisitCreateTemplateResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type CreateTemplateFromItemsRequestObject struct {
	Params CreateTemplateFromItemsParams
	Body   *CreateTemplateFromItemsJSONRequestBody
}

type CreateTemplateFromItemsResponseObject interface {
	VisitCreateTemplateFromItemsResponse(w http.ResponseWriter) error
}

type CreateTemplateFromItems201JSONResponse TemplateResponse

func (response CreateTemplateFromItems201JSONResponse) VisitCreateTemplateFromItemsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type CreateTemplateFromItems400JSONResponse Error

func (response CreateTemplateFromItems400JSONResponse) VisitCreateTemplateFromItemsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type CreateTemplateFromItems404JSONResponse Error

func (response CreateTemplateFromItems404JSONResponse) VisitCreateTemplateFromItemsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type CreateTemplateFromItems500JSONResponse Error

func (response CreateTemplateFromItems500JSONResponse) VisitCreateTemplateFromItemsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type DeleteTemplateRequestObject struct {
	TemplateId uint `json:"templateId"`
	Params     DeleteTemplateParams
}

type DeleteTemplateResponseObject interface {
	VisitDeleteTemplateResponse(w http.ResponseWriter) error
}

type DeleteTemplate204Response struct {
}

func (response DeleteTemplate204Response) VisitDeleteTemplateResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type DeleteTemplate404JSONResponse Error

func (response DeleteTemplate404JSONResponse) VisitDeleteTemplateResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type DeleteTemplate500JSONResponse Error

func (response DeleteTemplate500JSONResponse) VisitDeleteTemplateResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetTemplateByIdRequestObject struct {
	TemplateId uint `json:"templateId"`
	Params     GetTemplateByIdParams
}

type GetTemplateByIdResponseObject interface {
	VisitGetTemplateByIdResponse(w http.ResponseWriter) error
}

type GetTemplateById200JSONResponse TemplateResponse

func (response GetTemplateById200JSONResponse) VisitGetTemplateByIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetTemplateById404JSONResponse Error

func (response GetTemplateById404JSONResponse) VisitGetTemplateByIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type GetTemplateById500JSONResponse Error

func (response GetTemplateById500JSONResponse) VisitGetTemplateByIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type UpdateTemplateRequestObject struct {
	TemplateId uint `json:"templateId"`
	Params     UpdateTemplateParams
	Body       *UpdateTemplateJSONRequestBody
}

type UpdateTemplateResponseObject interface {
	VisitUpdateTemplateResponse(w http.ResponseWriter) error
}

type UpdateTemplate200JSONResponse TemplateResponse

func (response UpdateTemplate200JSONResponse) VisitUpdateTemplateResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type UpdateTemplate400JSONResponse Error

func (response UpdateTemplate400JSONResponse) VisitUpdateTemplateResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type UpdateTemplate404JSONResponse Error

func (response UpdateTemplate404JSONResponse) VisitUpdateTemplateResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type UpdateTemplate500JSONResponse Error

func (response UpdateTemplate500JSONResponse) VisitUpdateTemplateResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type CreateChecklistFromTemplateRequestObject struct {
	TemplateId uint `json:"templateId"`
	Params     CreateChecklistFromTemplateParams
	Body       *CreateChecklistFromTemplateJSONRequestBody
}

type CreateChecklistFromTemplateResponseObject interface {
	VisitCreateChecklistFromTemplateResponse(w http.ResponseWriter) error
}

type CreateChecklistFromTemplate201JSONResponse ChecklistResponse

func (response CreateChecklistFromTemplate201JSONResponse) VisitCreateChecklistFromTemplateResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type CreateChecklistFromTemplate400JSONResponse Error

func (response CreateChecklistFromTemplate400JSONResponse) VisitCreateChecklistFromTemplateResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type CreateChecklistFromTemplate404JSONResponse Error

func (response CreateChecklistFromTemplate404JSONResponse) VisitCreateChecklistFromTemplateResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type CreateChecklistFromTemplate500JSONResponse Error

func (response CreateChecklistFromTemplate500JSONResponse) VisitCreateChecklistFromTemplateResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Apply template to checklist
	// (POST /api/v1/checklists/{checklistId}/apply-template/{templateId})
	ApplyTemplate(ctx context.Context, request ApplyTemplateRequestObject) (ApplyTemplateResponseObject, error)
	// Get template preview with duplicate detection
	// (GET /api/v1/checklists/{checklistId}/template-preview/{templateId})
	GetTemplatePreview(ctx context.Context, request GetTemplatePreviewRequestObject) (GetTemplatePreviewResponseObject, error)
	// List all templates
	// (GET /api/v1/templates)
	GetAllTemplates(ctx context.Context, request GetAllTemplatesRequestObject) (GetAllTemplatesResponseObject, error)
	// Create a new template
	// (POST /api/v1/templates)
	CreateTemplate(ctx context.Context, request CreateTemplateRequestObject) (CreateTemplateResponseObject, error)
	// Create template from existing checklist items
	// (POST /api/v1/templates/from-items)
	CreateTemplateFromItems(ctx context.Context, request CreateTemplateFromItemsRequestObject) (CreateTemplateFromItemsResponseObject, error)
	// Delete template
	// (DELETE /api/v1/templates/{templateId})
	DeleteTemplate(ctx context.Context, request DeleteTemplateRequestObject) (DeleteTemplateResponseObject, error)
	// Get template by ID
	// (GET /api/v1/templates/{templateId})
	GetTemplateById(ctx context.Context, request GetTemplateByIdRequestObject) (GetTemplateByIdResponseObject, error)
	// Update template
	// (PUT /api/v1/templates/{templateId})
	UpdateTemplate(ctx context.Context, request UpdateTemplateRequestObject) (UpdateTemplateResponseObject, error)
	// Create a new checklist pre-populated with all template items
	// (POST /api/v1/templates/{templateId}/create-checklist)
	CreateChecklistFromTemplate(ctx context.Context, request CreateChecklistFromTemplateRequestObject) (CreateChecklistFromTemplateResponseObject, error)
}

type StrictHandlerFunc = strictgin.StrictGinHandlerFunc
type StrictMiddlewareFunc = strictgin.StrictGinMiddlewareFunc

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
}

// ApplyTemplate operation middleware
func (sh *strictHandler) ApplyTemplate(ctx *gin.Context, checklistId uint, templateId uint, params ApplyTemplateParams) {
	var request ApplyTemplateRequestObject

	request.ChecklistId = checklistId
	request.TemplateId = templateId
	request.Params = params

	var body ApplyTemplateJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		ctx.Status(http.StatusBadRequest)
		ctx.Error(err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.ApplyTemplate(ctx, request.(ApplyTemplateRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ApplyTemplate")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(ApplyTemplateResponseObject); ok {
		if err := validResponse.VisitApplyTemplateResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetTemplatePreview operation middleware
func (sh *strictHandler) GetTemplatePreview(ctx *gin.Context, checklistId uint, templateId uint, params GetTemplatePreviewParams) {
	var request GetTemplatePreviewRequestObject

	request.ChecklistId = checklistId
	request.TemplateId = templateId
	request.Params = params

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetTemplatePreview(ctx, request.(GetTemplatePreviewRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetTemplatePreview")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(GetTemplatePreviewResponseObject); ok {
		if err := validResponse.VisitGetTemplatePreviewResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetAllTemplates operation middleware
func (sh *strictHandler) GetAllTemplates(ctx *gin.Context, params GetAllTemplatesParams) {
	var request GetAllTemplatesRequestObject

	request.Params = params

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetAllTemplates(ctx, request.(GetAllTemplatesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetAllTemplates")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(GetAllTemplatesResponseObject); ok {
		if err := validResponse.VisitGetAllTemplatesResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateTemplate operation middleware
func (sh *strictHandler) CreateTemplate(ctx *gin.Context, params CreateTemplateParams) {
	var request CreateTemplateRequestObject

	request.Params = params

	var body CreateTemplateJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		ctx.Status(http.StatusBadRequest)
		ctx.Error(err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.CreateTemplate(ctx, request.(CreateTemplateRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateTemplate")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(CreateTemplateResponseObject); ok {
		if err := validResponse.VisitCreateTemplateResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateTemplateFromItems operation middleware
func (sh *strictHandler) CreateTemplateFromItems(ctx *gin.Context, params CreateTemplateFromItemsParams) {
	var request CreateTemplateFromItemsRequestObject

	request.Params = params

	var body CreateTemplateFromItemsJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		ctx.Status(http.StatusBadRequest)
		ctx.Error(err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.CreateTemplateFromItems(ctx, request.(CreateTemplateFromItemsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateTemplateFromItems")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(CreateTemplateFromItemsResponseObject); ok {
		if err := validResponse.VisitCreateTemplateFromItemsResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeleteTemplate operation middleware
func (sh *strictHandler) DeleteTemplate(ctx *gin.Context, templateId uint, params DeleteTemplateParams) {
	var request DeleteTemplateRequestObject

	request.TemplateId = templateId
	request.Params = params

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteTemplate(ctx, request.(DeleteTemplateRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteTemplate")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(DeleteTemplateResponseObject); ok {
		if err := validResponse.VisitDeleteTemplateResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetTemplateById operation middleware
func (sh *strictHandler) GetTemplateById(ctx *gin.Context, templateId uint, params GetTemplateByIdParams) {
	var request GetTemplateByIdRequestObject

	request.TemplateId = templateId
	request.Params = params

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetTemplateById(ctx, request.(GetTemplateByIdRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetTemplateById")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(GetTemplateByIdResponseObject); ok {
		if err := validResponse.VisitGetTemplateByIdResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// UpdateTemplate operation middleware
func (sh *strictHandler) UpdateTemplate(ctx *gin.Context, templateId uint, params UpdateTemplateParams) {
	var request UpdateTemplateRequestObject

	request.TemplateId = templateId
	request.Params = params

	var body UpdateTemplateJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		ctx.Status(http.StatusBadRequest)
		ctx.Error(err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.UpdateTemplate(ctx, request.(UpdateTemplateRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UpdateTemplate")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(UpdateTemplateResponseObject); ok {
		if err := validResponse.VisitUpdateTemplateResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateChecklistFromTemplate operation middleware
func (sh *strictHandler) CreateChecklistFromTemplate(ctx *gin.Context, templateId uint, params CreateChecklistFromTemplateParams) {
	var request CreateChecklistFromTemplateRequestObject

	request.TemplateId = templateId
	request.Params = params

	var body CreateChecklistFromTemplateJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		ctx.Status(http.StatusBadRequest)
		ctx.Error(err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.CreateChecklistFromTemplate(ctx, request.(CreateChecklistFromTemplateRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateChecklistFromTemplate")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(CreateChecklistFromTemplateResponseObject); ok {
		if err := validResponse.VisitCreateChecklistFromTemplateResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}
