// Package workspace provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package workspace

import (
	"context"
	"encoding/json"
	"fmt"
	"net/http"
	"time"

	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
	strictgin "github.com/oapi-codegen/runtime/strictmiddleware/gin"
)

const (
	CookieAuthScopes = "CookieAuth.Scopes"
)

// ChecklistWithStats defines model for ChecklistWithStats.
type ChecklistWithStats struct {
	Id uint `json:"id"`

	// IsOwner Is current user owner of the checklist
	IsOwner bool `json:"isOwner"`

	// IsShared Whether this checklist is shared with others (only true for owners)
	IsShared bool   `json:"isShared"`
	Name     string `json:"name"`

	// NumberOfSharedUsers Number of users this checklist is shared with (only included for owners)
	NumberOfSharedUsers *float32 `json:"numberOfSharedUsers,omitempty"`

	// Stats Statistics about checklist items
	Stats struct {
		// CompletedItems Number of completed items
		CompletedItems uint `json:"completedItems"`

		// TotalItems Total number of items in the checklist
		TotalItems uint `json:"totalItems"`
	} `json:"stats"`

	// WorkspaceId Circle this checklist belongs to
	WorkspaceId *int `json:"workspaceId"`
}

// ClaimWorkspaceInviteResponse defines model for ClaimWorkspaceInviteResponse.
type ClaimWorkspaceInviteResponse struct {
	Message     *string `json:"message,omitempty"`
	WorkspaceId uint    `json:"workspaceId"`
}

// CreateInviteRequest defines model for CreateInviteRequest.
type CreateInviteRequest struct {
	// ExpiresInHours Hours until invite expires (null = never expires)
	ExpiresInHours *int `json:"expiresInHours"`

	// IsSingleUse If true, invite can only be claimed once
	IsSingleUse bool `json:"isSingleUse"`

	// Name Optional friendly name for the invite (e.g., "For John", "Team members")
	Name *string `json:"name"`
}

// CreateWorkspaceRequest defines model for CreateWorkspaceRequest.
type CreateWorkspaceRequest struct {
	Description *string `json:"description"`
	Name        string  `json:"name"`
}

// Error defines model for Error.
type Error struct {
	Message string `json:"message"`
}

// TemplateResponse defines model for TemplateResponse.
type TemplateResponse struct {
	CreatedAt   time.Time `json:"createdAt"`
	Description *string   `json:"description"`
	Id          uint      `json:"id"`

	// IsOwner True if the current user owns this template, false if shared
	IsOwner   bool                  `json:"isOwner"`
	Name      string                `json:"name"`
	Rows      []TemplateRowResponse `json:"rows"`
	UpdatedAt time.Time             `json:"updatedAt"`
	UserId    string                `json:"userId"`

	// WorkspaceIds Circles this template belongs to
	WorkspaceIds []uint `json:"workspaceIds"`
}

// TemplateRowResponse defines model for TemplateRowResponse.
type TemplateRowResponse struct {
	CreatedAt  time.Time `json:"createdAt"`
	Id         uint      `json:"id"`
	Name       string    `json:"name"`
	Position   float64   `json:"position"`
	TemplateId uint      `json:"templateId"`
	UpdatedAt  time.Time `json:"updatedAt"`
}

// WorkspaceInviteResponse defines model for WorkspaceInviteResponse.
type WorkspaceInviteResponse struct {
	ClaimedAt   *time.Time `json:"claimedAt"`
	ClaimedBy   *string    `json:"claimedBy"`
	CreatedAt   time.Time  `json:"createdAt"`
	ExpiresAt   *time.Time `json:"expiresAt"`
	Id          uint       `json:"id"`
	InviteToken string     `json:"inviteToken"`
	InviteUrl   string     `json:"inviteUrl"`
	IsClaimed   bool       `json:"isClaimed"`
	IsExpired   bool       `json:"isExpired"`
	IsSingleUse bool       `json:"isSingleUse"`
	Name        *string    `json:"name"`
	WorkspaceId uint       `json:"workspaceId"`
}

// WorkspaceMemberResponse defines model for WorkspaceMemberResponse.
type WorkspaceMemberResponse struct {
	Email   string  `json:"email"`
	IsOwner bool    `json:"isOwner"`
	Name    *string `json:"name"`
	UserId  string  `json:"userId"`
}

// WorkspaceResponse defines model for WorkspaceResponse.
type WorkspaceResponse struct {
	Description *string `json:"description"`
	Id          uint    `json:"id"`
	IsDefault   bool    `json:"isDefault"`
	IsOwner     bool    `json:"isOwner"`
	MemberCount int     `json:"memberCount"`
	Name        string  `json:"name"`
}

// XClientId defines model for X-Client-Id.
type XClientId = string

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse = Error

// ClaimWorkspaceInviteParams defines parameters for ClaimWorkspaceInvite.
type ClaimWorkspaceInviteParams struct {
	// XClientId Client identifier sent by frontend in headers
	XClientId *XClientId `json:"X-Client-Id,omitempty"`
}

// GetAllWorkspacesParams defines parameters for GetAllWorkspaces.
type GetAllWorkspacesParams struct {
	// XClientId Client identifier sent by frontend in headers
	XClientId *XClientId `json:"X-Client-Id,omitempty"`
}

// CreateWorkspaceParams defines parameters for CreateWorkspace.
type CreateWorkspaceParams struct {
	// XClientId Client identifier sent by frontend in headers
	XClientId *XClientId `json:"X-Client-Id,omitempty"`
}

// DeleteWorkspaceParams defines parameters for DeleteWorkspace.
type DeleteWorkspaceParams struct {
	// XClientId Client identifier sent by frontend in headers
	XClientId *XClientId `json:"X-Client-Id,omitempty"`
}

// GetWorkspaceByIdParams defines parameters for GetWorkspaceById.
type GetWorkspaceByIdParams struct {
	// XClientId Client identifier sent by frontend in headers
	XClientId *XClientId `json:"X-Client-Id,omitempty"`
}

// UpdateWorkspaceParams defines parameters for UpdateWorkspace.
type UpdateWorkspaceParams struct {
	// XClientId Client identifier sent by frontend in headers
	XClientId *XClientId `json:"X-Client-Id,omitempty"`
}

// GetWorkspaceChecklistsParams defines parameters for GetWorkspaceChecklists.
type GetWorkspaceChecklistsParams struct {
	// XClientId Client identifier sent by frontend in headers
	XClientId *XClientId `json:"X-Client-Id,omitempty"`
}

// GetWorkspaceInvitesParams defines parameters for GetWorkspaceInvites.
type GetWorkspaceInvitesParams struct {
	// XClientId Client identifier sent by frontend in headers
	XClientId *XClientId `json:"X-Client-Id,omitempty"`
}

// CreateWorkspaceInviteParams defines parameters for CreateWorkspaceInvite.
type CreateWorkspaceInviteParams struct {
	// XClientId Client identifier sent by frontend in headers
	XClientId *XClientId `json:"X-Client-Id,omitempty"`
}

// RevokeWorkspaceInviteParams defines parameters for RevokeWorkspaceInvite.
type RevokeWorkspaceInviteParams struct {
	// XClientId Client identifier sent by frontend in headers
	XClientId *XClientId `json:"X-Client-Id,omitempty"`
}

// LeaveWorkspaceParams defines parameters for LeaveWorkspace.
type LeaveWorkspaceParams struct {
	// XClientId Client identifier sent by frontend in headers
	XClientId *XClientId `json:"X-Client-Id,omitempty"`
}

// GetWorkspaceMembersParams defines parameters for GetWorkspaceMembers.
type GetWorkspaceMembersParams struct {
	// XClientId Client identifier sent by frontend in headers
	XClientId *XClientId `json:"X-Client-Id,omitempty"`
}

// RemoveWorkspaceMemberParams defines parameters for RemoveWorkspaceMember.
type RemoveWorkspaceMemberParams struct {
	// XClientId Client identifier sent by frontend in headers
	XClientId *XClientId `json:"X-Client-Id,omitempty"`
}

// GetWorkspaceTemplatesParams defines parameters for GetWorkspaceTemplates.
type GetWorkspaceTemplatesParams struct {
	// XClientId Client identifier sent by frontend in headers
	XClientId *XClientId `json:"X-Client-Id,omitempty"`
}

// CreateWorkspaceJSONRequestBody defines body for CreateWorkspace for application/json ContentType.
type CreateWorkspaceJSONRequestBody = CreateWorkspaceRequest

// UpdateWorkspaceJSONRequestBody defines body for UpdateWorkspace for application/json ContentType.
type UpdateWorkspaceJSONRequestBody = CreateWorkspaceRequest

// CreateWorkspaceInviteJSONRequestBody defines body for CreateWorkspaceInvite for application/json ContentType.
type CreateWorkspaceInviteJSONRequestBody = CreateInviteRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Claim a workspace invite
	// (POST /api/v1/workspace-invites/{token}/claim)
	ClaimWorkspaceInvite(c *gin.Context, token string, params ClaimWorkspaceInviteParams)
	// Get all workspaces for current user
	// (GET /api/v1/workspaces)
	GetAllWorkspaces(c *gin.Context, params GetAllWorkspacesParams)
	// Create a new workspace
	// (POST /api/v1/workspaces)
	CreateWorkspace(c *gin.Context, params CreateWorkspaceParams)
	// Delete workspace
	// (DELETE /api/v1/workspaces/{workspaceId})
	DeleteWorkspace(c *gin.Context, workspaceId uint, params DeleteWorkspaceParams)
	// Get workspace by ID
	// (GET /api/v1/workspaces/{workspaceId})
	GetWorkspaceById(c *gin.Context, workspaceId uint, params GetWorkspaceByIdParams)
	// Update workspace
	// (PUT /api/v1/workspaces/{workspaceId})
	UpdateWorkspace(c *gin.Context, workspaceId uint, params UpdateWorkspaceParams)
	// Get checklists in a workspace
	// (GET /api/v1/workspaces/{workspaceId}/checklists)
	GetWorkspaceChecklists(c *gin.Context, workspaceId uint, params GetWorkspaceChecklistsParams)
	// List active invite links for a workspace
	// (GET /api/v1/workspaces/{workspaceId}/invites)
	GetWorkspaceInvites(c *gin.Context, workspaceId uint, params GetWorkspaceInvitesParams)
	// Create a new workspace invite link
	// (POST /api/v1/workspaces/{workspaceId}/invites)
	CreateWorkspaceInvite(c *gin.Context, workspaceId uint, params CreateWorkspaceInviteParams)
	// Revoke a workspace invite link
	// (DELETE /api/v1/workspaces/{workspaceId}/invites/{inviteId})
	RevokeWorkspaceInvite(c *gin.Context, workspaceId uint, inviteId uint, params RevokeWorkspaceInviteParams)
	// Leave a workspace
	// (POST /api/v1/workspaces/{workspaceId}/leave)
	LeaveWorkspace(c *gin.Context, workspaceId uint, params LeaveWorkspaceParams)
	// Get workspace members
	// (GET /api/v1/workspaces/{workspaceId}/members)
	GetWorkspaceMembers(c *gin.Context, workspaceId uint, params GetWorkspaceMembersParams)
	// Remove a member from workspace
	// (DELETE /api/v1/workspaces/{workspaceId}/members/{userId})
	RemoveWorkspaceMember(c *gin.Context, workspaceId uint, userId string, params RemoveWorkspaceMemberParams)
	// Get templates in a workspace
	// (GET /api/v1/workspaces/{workspaceId}/templates)
	GetWorkspaceTemplates(c *gin.Context, workspaceId uint, params GetWorkspaceTemplatesParams)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// ClaimWorkspaceInvite operation middleware
func (siw *ServerInterfaceWrapper) ClaimWorkspaceInvite(c *gin.Context) {

	var err error

	// ------------- Path parameter "token" -------------
	var token string

	err = runtime.BindStyledParameterWithOptions("simple", "token", c.Param("token"), &token, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter token: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(CookieAuthScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params ClaimWorkspaceInviteParams

	headers := c.Request.Header

	// ------------- Optional header parameter "X-Client-Id" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Client-Id")]; found {
		var XClientId XClientId
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandler(c, fmt.Errorf("Expected one value for X-Client-Id, got %d", n), http.StatusBadRequest)
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Client-Id", valueList[0], &XClientId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false})
		if err != nil {
			siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter X-Client-Id: %w", err), http.StatusBadRequest)
			return
		}

		params.XClientId = &XClientId

	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ClaimWorkspaceInvite(c, token, params)
}

// GetAllWorkspaces operation middleware
func (siw *ServerInterfaceWrapper) GetAllWorkspaces(c *gin.Context) {

	var err error

	c.Set(CookieAuthScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params GetAllWorkspacesParams

	headers := c.Request.Header

	// ------------- Optional header parameter "X-Client-Id" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Client-Id")]; found {
		var XClientId XClientId
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandler(c, fmt.Errorf("Expected one value for X-Client-Id, got %d", n), http.StatusBadRequest)
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Client-Id", valueList[0], &XClientId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false})
		if err != nil {
			siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter X-Client-Id: %w", err), http.StatusBadRequest)
			return
		}

		params.XClientId = &XClientId

	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetAllWorkspaces(c, params)
}

// CreateWorkspace operation middleware
func (siw *ServerInterfaceWrapper) CreateWorkspace(c *gin.Context) {

	var err error

	c.Set(CookieAuthScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params CreateWorkspaceParams

	headers := c.Request.Header

	// ------------- Optional header parameter "X-Client-Id" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Client-Id")]; found {
		var XClientId XClientId
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandler(c, fmt.Errorf("Expected one value for X-Client-Id, got %d", n), http.StatusBadRequest)
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Client-Id", valueList[0], &XClientId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false})
		if err != nil {
			siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter X-Client-Id: %w", err), http.StatusBadRequest)
			return
		}

		params.XClientId = &XClientId

	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateWorkspace(c, params)
}

// DeleteWorkspace operation middleware
func (siw *ServerInterfaceWrapper) DeleteWorkspace(c *gin.Context) {

	var err error

	// ------------- Path parameter "workspaceId" -------------
	var workspaceId uint

	err = runtime.BindStyledParameterWithOptions("simple", "workspaceId", c.Param("workspaceId"), &workspaceId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter workspaceId: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(CookieAuthScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params DeleteWorkspaceParams

	headers := c.Request.Header

	// ------------- Optional header parameter "X-Client-Id" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Client-Id")]; found {
		var XClientId XClientId
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandler(c, fmt.Errorf("Expected one value for X-Client-Id, got %d", n), http.StatusBadRequest)
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Client-Id", valueList[0], &XClientId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false})
		if err != nil {
			siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter X-Client-Id: %w", err), http.StatusBadRequest)
			return
		}

		params.XClientId = &XClientId

	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DeleteWorkspace(c, workspaceId, params)
}

// GetWorkspaceById operation middleware
func (siw *ServerInterfaceWrapper) GetWorkspaceById(c *gin.Context) {

	var err error

	// ------------- Path parameter "workspaceId" -------------
	var workspaceId uint

	err = runtime.BindStyledParameterWithOptions("simple", "workspaceId", c.Param("workspaceId"), &workspaceId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter workspaceId: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(CookieAuthScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params GetWorkspaceByIdParams

	headers := c.Request.Header

	// ------------- Optional header parameter "X-Client-Id" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Client-Id")]; found {
		var XClientId XClientId
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandler(c, fmt.Errorf("Expected one value for X-Client-Id, got %d", n), http.StatusBadRequest)
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Client-Id", valueList[0], &XClientId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false})
		if err != nil {
			siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter X-Client-Id: %w", err), http.StatusBadRequest)
			return
		}

		params.XClientId = &XClientId

	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetWorkspaceById(c, workspaceId, params)
}

// UpdateWorkspace operation middleware
func (siw *ServerInterfaceWrapper) UpdateWorkspace(c *gin.Context) {

	var err error

	// ------------- Path parameter "workspaceId" -------------
	var workspaceId uint

	err = runtime.BindStyledParameterWithOptions("simple", "workspaceId", c.Param("workspaceId"), &workspaceId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter workspaceId: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(CookieAuthScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params UpdateWorkspaceParams

	headers := c.Request.Header

	// ------------- Optional header parameter "X-Client-Id" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Client-Id")]; found {
		var XClientId XClientId
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandler(c, fmt.Errorf("Expected one value for X-Client-Id, got %d", n), http.StatusBadRequest)
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Client-Id", valueList[0], &XClientId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false})
		if err != nil {
			siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter X-Client-Id: %w", err), http.StatusBadRequest)
			return
		}

		params.XClientId = &XClientId

	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.UpdateWorkspace(c, workspaceId, params)
}

// GetWorkspaceChecklists operation middleware
func (siw *ServerInterfaceWrapper) GetWorkspaceChecklists(c *gin.Context) {

	var err error

	// ------------- Path parameter "workspaceId" -------------
	var workspaceId uint

	err = runtime.BindStyledParameterWithOptions("simple", "workspaceId", c.Param("workspaceId"), &workspaceId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter workspaceId: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(CookieAuthScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params GetWorkspaceChecklistsParams

	headers := c.Request.Header

	// ------------- Optional header parameter "X-Client-Id" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Client-Id")]; found {
		var XClientId XClientId
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandler(c, fmt.Errorf("Expected one value for X-Client-Id, got %d", n), http.StatusBadRequest)
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Client-Id", valueList[0], &XClientId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false})
		if err != nil {
			siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter X-Client-Id: %w", err), http.StatusBadRequest)
			return
		}

		params.XClientId = &XClientId

	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetWorkspaceChecklists(c, workspaceId, params)
}

// GetWorkspaceInvites operation middleware
func (siw *ServerInterfaceWrapper) GetWorkspaceInvites(c *gin.Context) {

	var err error

	// ------------- Path parameter "workspaceId" -------------
	var workspaceId uint

	err = runtime.BindStyledParameterWithOptions("simple", "workspaceId", c.Param("workspaceId"), &workspaceId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter workspaceId: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(CookieAuthScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params GetWorkspaceInvitesParams

	headers := c.Request.Header

	// ------------- Optional header parameter "X-Client-Id" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Client-Id")]; found {
		var XClientId XClientId
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandler(c, fmt.Errorf("Expected one value for X-Client-Id, got %d", n), http.StatusBadRequest)
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Client-Id", valueList[0], &XClientId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false})
		if err != nil {
			siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter X-Client-Id: %w", err), http.StatusBadRequest)
			return
		}

		params.XClientId = &XClientId

	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetWorkspaceInvites(c, workspaceId, params)
}

// CreateWorkspaceInvite operation middleware
func (siw *ServerInterfaceWrapper) CreateWorkspaceInvite(c *gin.Context) {

	var err error

	// ------------- Path parameter "workspaceId" -------------
	var workspaceId uint

	err = runtime.BindStyledParameterWithOptions("simple", "workspaceId", c.Param("workspaceId"), &workspaceId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter workspaceId: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(CookieAuthScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params CreateWorkspaceInviteParams

	headers := c.Request.Header

	// ------------- Optional header parameter "X-Client-Id" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Client-Id")]; found {
		var XClientId XClientId
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandler(c, fmt.Errorf("Expected one value for X-Client-Id, got %d", n), http.StatusBadRequest)
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Client-Id", valueList[0], &XClientId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false})
		if err != nil {
			siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter X-Client-Id: %w", err), http.StatusBadRequest)
			return
		}

		params.XClientId = &XClientId

	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateWorkspaceInvite(c, workspaceId, params)
}

// RevokeWorkspaceInvite operation middleware
func (siw *ServerInterfaceWrapper) RevokeWorkspaceInvite(c *gin.Context) {

	var err error

	// ------------- Path parameter "workspaceId" -------------
	var workspaceId uint

	err = runtime.BindStyledParameterWithOptions("simple", "workspaceId", c.Param("workspaceId"), &workspaceId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter workspaceId: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Path parameter "inviteId" -------------
	var inviteId uint

	err = runtime.BindStyledParameterWithOptions("simple", "inviteId", c.Param("inviteId"), &inviteId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter inviteId: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(CookieAuthScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params RevokeWorkspaceInviteParams

	headers := c.Request.Header

	// ------------- Optional header parameter "X-Client-Id" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Client-Id")]; found {
		var XClientId XClientId
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandler(c, fmt.Errorf("Expected one value for X-Client-Id, got %d", n), http.StatusBadRequest)
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Client-Id", valueList[0], &XClientId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false})
		if err != nil {
			siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter X-Client-Id: %w", err), http.StatusBadRequest)
			return
		}

		params.XClientId = &XClientId

	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.RevokeWorkspaceInvite(c, workspaceId, inviteId, params)
}

// LeaveWorkspace operation middleware
func (siw *ServerInterfaceWrapper) LeaveWorkspace(c *gin.Context) {

	var err error

	// ------------- Path parameter "workspaceId" -------------
	var workspaceId uint

	err = runtime.BindStyledParameterWithOptions("simple", "workspaceId", c.Param("workspaceId"), &workspaceId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter workspaceId: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(CookieAuthScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params LeaveWorkspaceParams

	headers := c.Request.Header

	// ------------- Optional header parameter "X-Client-Id" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Client-Id")]; found {
		var XClientId XClientId
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandler(c, fmt.Errorf("Expected one value for X-Client-Id, got %d", n), http.StatusBadRequest)
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Client-Id", valueList[0], &XClientId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false})
		if err != nil {
			siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter X-Client-Id: %w", err), http.StatusBadRequest)
			return
		}

		params.XClientId = &XClientId

	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.LeaveWorkspace(c, workspaceId, params)
}

// GetWorkspaceMembers operation middleware
func (siw *ServerInterfaceWrapper) GetWorkspaceMembers(c *gin.Context) {

	var err error

	// ------------- Path parameter "workspaceId" -------------
	var workspaceId uint

	err = runtime.BindStyledParameterWithOptions("simple", "workspaceId", c.Param("workspaceId"), &workspaceId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter workspaceId: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(CookieAuthScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params GetWorkspaceMembersParams

	headers := c.Request.Header

	// ------------- Optional header parameter "X-Client-Id" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Client-Id")]; found {
		var XClientId XClientId
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandler(c, fmt.Errorf("Expected one value for X-Client-Id, got %d", n), http.StatusBadRequest)
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Client-Id", valueList[0], &XClientId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false})
		if err != nil {
			siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter X-Client-Id: %w", err), http.StatusBadRequest)
			return
		}

		params.XClientId = &XClientId

	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetWorkspaceMembers(c, workspaceId, params)
}

// RemoveWorkspaceMember operation middleware
func (siw *ServerInterfaceWrapper) RemoveWorkspaceMember(c *gin.Context) {

	var err error

	// ------------- Path parameter "workspaceId" -------------
	var workspaceId uint

	err = runtime.BindStyledParameterWithOptions("simple", "workspaceId", c.Param("workspaceId"), &workspaceId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter workspaceId: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Path parameter "userId" -------------
	var userId string

	err = runtime.BindStyledParameterWithOptions("simple", "userId", c.Param("userId"), &userId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter userId: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(CookieAuthScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params RemoveWorkspaceMemberParams

	headers := c.Request.Header

	// ------------- Optional header parameter "X-Client-Id" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Client-Id")]; found {
		var XClientId XClientId
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandler(c, fmt.Errorf("Expected one value for X-Client-Id, got %d", n), http.StatusBadRequest)
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Client-Id", valueList[0], &XClientId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false})
		if err != nil {
			siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter X-Client-Id: %w", err), http.StatusBadRequest)
			return
		}

		params.XClientId = &XClientId

	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.RemoveWorkspaceMember(c, workspaceId, userId, params)
}

// GetWorkspaceTemplates operation middleware
func (siw *ServerInterfaceWrapper) GetWorkspaceTemplates(c *gin.Context) {

	var err error

	// ------------- Path parameter "workspaceId" -------------
	var workspaceId uint

	err = runtime.BindStyledParameterWithOptions("simple", "workspaceId", c.Param("workspaceId"), &workspaceId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter workspaceId: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(CookieAuthScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params GetWorkspaceTemplatesParams

	headers := c.Request.Header

	// ------------- Optional header parameter "X-Client-Id" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Client-Id")]; found {
		var XClientId XClientId
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandler(c, fmt.Errorf("Expected one value for X-Client-Id, got %d", n), http.StatusBadRequest)
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Client-Id", valueList[0], &XClientId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false})
		if err != nil {
			siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter X-Client-Id: %w", err), http.StatusBadRequest)
			return
		}

		params.XClientId = &XClientId

	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetWorkspaceTemplates(c, workspaceId, params)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.POST(options.BaseURL+"/api/v1/workspace-invites/:token/claim", wrapper.ClaimWorkspaceInvite)
	router.GET(options.BaseURL+"/api/v1/workspaces", wrapper.GetAllWorkspaces)
	router.POST(options.BaseURL+"/api/v1/workspaces", wrapper.CreateWorkspace)
	router.DELETE(options.BaseURL+"/api/v1/workspaces/:workspaceId", wrapper.DeleteWorkspace)
	router.GET(options.BaseURL+"/api/v1/workspaces/:workspaceId", wrapper.GetWorkspaceById)
	router.PUT(options.BaseURL+"/api/v1/workspaces/:workspaceId", wrapper.UpdateWorkspace)
	router.GET(options.BaseURL+"/api/v1/workspaces/:workspaceId/checklists", wrapper.GetWorkspaceChecklists)
	router.GET(options.BaseURL+"/api/v1/workspaces/:workspaceId/invites", wrapper.GetWorkspaceInvites)
	router.POST(options.BaseURL+"/api/v1/workspaces/:workspaceId/invites", wrapper.CreateWorkspaceInvite)
	router.DELETE(options.BaseURL+"/api/v1/workspaces/:workspaceId/invites/:inviteId", wrapper.RevokeWorkspaceInvite)
	router.POST(options.BaseURL+"/api/v1/workspaces/:workspaceId/leave", wrapper.LeaveWorkspace)
	router.GET(options.BaseURL+"/api/v1/workspaces/:workspaceId/members", wrapper.GetWorkspaceMembers)
	router.DELETE(options.BaseURL+"/api/v1/workspaces/:workspaceId/members/:userId", wrapper.RemoveWorkspaceMember)
	router.GET(options.BaseURL+"/api/v1/workspaces/:workspaceId/templates", wrapper.GetWorkspaceTemplates)
}

type ErrorResponseJSONResponse Error

type ClaimWorkspaceInviteRequestObject struct {
	Token  string `json:"token"`
	Params ClaimWorkspaceInviteParams
}

type ClaimWorkspaceInviteResponseObject interface {
	VisitClaimWorkspaceInviteResponse(w http.ResponseWriter) error
}

type ClaimWorkspaceInvite200JSONResponse ClaimWorkspaceInviteResponse

func (response ClaimWorkspaceInvite200JSONResponse) VisitClaimWorkspaceInviteResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type ClaimWorkspaceInvite400JSONResponse struct{ ErrorResponseJSONResponse }

func (response ClaimWorkspaceInvite400JSONResponse) VisitClaimWorkspaceInviteResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type ClaimWorkspaceInvite401JSONResponse Error

func (response ClaimWorkspaceInvite401JSONResponse) VisitClaimWorkspaceInviteResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type ClaimWorkspaceInvite404JSONResponse Error

func (response ClaimWorkspaceInvite404JSONResponse) VisitClaimWorkspaceInviteResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type ClaimWorkspaceInvite500JSONResponse Error

func (response ClaimWorkspaceInvite500JSONResponse) VisitClaimWorkspaceInviteResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetAllWorkspacesRequestObject struct {
	Params GetAllWorkspacesParams
}

type GetAllWorkspacesResponseObject interface {
	VisitGetAllWorkspacesResponse(w http.ResponseWriter) error
}

type GetAllWorkspaces200JSONResponse []WorkspaceResponse

func (response GetAllWorkspaces200JSONResponse) VisitGetAllWorkspacesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetAllWorkspaces500JSONResponse struct{ ErrorResponseJSONResponse }

func (response GetAllWorkspaces500JSONResponse) VisitGetAllWorkspacesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type CreateWorkspaceRequestObject struct {
	Params CreateWorkspaceParams
	Body   *CreateWorkspaceJSONRequestBody
}

type CreateWorkspaceResponseObject interface {
	VisitCreateWorkspaceResponse(w http.ResponseWriter) error
}

type CreateWorkspace201JSONResponse WorkspaceResponse

func (response CreateWorkspace201JSONResponse) VisitCreateWorkspaceResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type CreateWorkspace400JSONResponse struct{ ErrorResponseJSONResponse }

func (response CreateWorkspace400JSONResponse) VisitCreateWorkspaceResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type CreateWorkspace500JSONResponse Error

func (response CreateWorkspace500JSONResponse) VisitCreateWorkspaceResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type DeleteWorkspaceRequestObject struct {
	WorkspaceId uint `json:"workspaceId"`
	Params      DeleteWorkspaceParams
}

type DeleteWorkspaceResponseObject interface {
	VisitDeleteWorkspaceResponse(w http.ResponseWriter) error
}

type DeleteWorkspace204Response struct {
}

func (response DeleteWorkspace204Response) VisitDeleteWorkspaceResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type DeleteWorkspace403JSONResponse struct{ ErrorResponseJSONResponse }

func (response DeleteWorkspace403JSONResponse) VisitDeleteWorkspaceResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type DeleteWorkspace404JSONResponse Error

func (response DeleteWorkspace404JSONResponse) VisitDeleteWorkspaceResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type DeleteWorkspace500JSONResponse Error

func (response DeleteWorkspace500JSONResponse) VisitDeleteWorkspaceResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetWorkspaceByIdRequestObject struct {
	WorkspaceId uint `json:"workspaceId"`
	Params      GetWorkspaceByIdParams
}

type GetWorkspaceByIdResponseObject interface {
	VisitGetWorkspaceByIdResponse(w http.ResponseWriter) error
}

type GetWorkspaceById200JSONResponse WorkspaceResponse

func (response GetWorkspaceById200JSONResponse) VisitGetWorkspaceByIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetWorkspaceById403JSONResponse struct{ ErrorResponseJSONResponse }

func (response GetWorkspaceById403JSONResponse) VisitGetWorkspaceByIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type GetWorkspaceById404JSONResponse Error

func (response GetWorkspaceById404JSONResponse) VisitGetWorkspaceByIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type GetWorkspaceById500JSONResponse Error

func (response GetWorkspaceById500JSONResponse) VisitGetWorkspaceByIdResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type UpdateWorkspaceRequestObject struct {
	WorkspaceId uint `json:"workspaceId"`
	Params      UpdateWorkspaceParams
	Body        *UpdateWorkspaceJSONRequestBody
}

type UpdateWorkspaceResponseObject interface {
	VisitUpdateWorkspaceResponse(w http.ResponseWriter) error
}

type UpdateWorkspace200JSONResponse WorkspaceResponse

func (response UpdateWorkspace200JSONResponse) VisitUpdateWorkspaceResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type UpdateWorkspace403JSONResponse struct{ ErrorResponseJSONResponse }

func (response UpdateWorkspace403JSONResponse) VisitUpdateWorkspaceResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type UpdateWorkspace404JSONResponse Error

func (response UpdateWorkspace404JSONResponse) VisitUpdateWorkspaceResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type UpdateWorkspace500JSONResponse Error

func (response UpdateWorkspace500JSONResponse) VisitUpdateWorkspaceResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetWorkspaceChecklistsRequestObject struct {
	WorkspaceId uint `json:"workspaceId"`
	Params      GetWorkspaceChecklistsParams
}

type GetWorkspaceChecklistsResponseObject interface {
	VisitGetWorkspaceChecklistsResponse(w http.ResponseWriter) error
}

type GetWorkspaceChecklists200JSONResponse []ChecklistWithStats

func (response GetWorkspaceChecklists200JSONResponse) VisitGetWorkspaceChecklistsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetWorkspaceChecklists403JSONResponse struct{ ErrorResponseJSONResponse }

func (response GetWorkspaceChecklists403JSONResponse) VisitGetWorkspaceChecklistsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type GetWorkspaceChecklists404JSONResponse Error

func (response GetWorkspaceChecklists404JSONResponse) VisitGetWorkspaceChecklistsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type GetWorkspaceChecklists500JSONResponse Error

func (response GetWorkspaceChecklists500JSONResponse) VisitGetWorkspaceChecklistsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetWorkspaceInvitesRequestObject struct {
	WorkspaceId uint `json:"workspaceId"`
	Params      GetWorkspaceInvitesParams
}

type GetWorkspaceInvitesResponseObject interface {
	VisitGetWorkspaceInvitesResponse(w http.ResponseWriter) error
}

type GetWorkspaceInvites200JSONResponse []WorkspaceInviteResponse

func (response GetWorkspaceInvites200JSONResponse) VisitGetWorkspaceInvitesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetWorkspaceInvites403JSONResponse struct{ ErrorResponseJSONResponse }

func (response GetWorkspaceInvites403JSONResponse) VisitGetWorkspaceInvitesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type GetWorkspaceInvites404JSONResponse Error

func (response GetWorkspaceInvites404JSONResponse) VisitGetWorkspaceInvitesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type GetWorkspaceInvites500JSONResponse Error

func (response GetWorkspaceInvites500JSONResponse) VisitGetWorkspaceInvitesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type CreateWorkspaceInviteRequestObject struct {
	WorkspaceId uint `json:"workspaceId"`
	Params      CreateWorkspaceInviteParams
	Body        *CreateWorkspaceInviteJSONRequestBody
}

type CreateWorkspaceInviteResponseObject interface {
	VisitCreateWorkspaceInviteResponse(w http.ResponseWriter) error
}

type CreateWorkspaceInvite201JSONResponse WorkspaceInviteResponse

func (response CreateWorkspaceInvite201JSONResponse) VisitCreateWorkspaceInviteResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type CreateWorkspaceInvite400JSONResponse struct{ ErrorResponseJSONResponse }

func (response CreateWorkspaceInvite400JSONResponse) VisitCreateWorkspaceInviteResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type CreateWorkspaceInvite403JSONResponse Error

func (response CreateWorkspaceInvite403JSONResponse) VisitCreateWorkspaceInviteResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type CreateWorkspaceInvite404JSONResponse Error

func (response CreateWorkspaceInvite404JSONResponse) VisitCreateWorkspaceInviteResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type CreateWorkspaceInvite500JSONResponse Error

func (response CreateWorkspaceInvite500JSONResponse) VisitCreateWorkspaceInviteResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type RevokeWorkspaceInviteRequestObject struct {
	WorkspaceId uint `json:"workspaceId"`
	InviteId    uint `json:"inviteId"`
	Params      RevokeWorkspaceInviteParams
}

type RevokeWorkspaceInviteResponseObject interface {
	VisitRevokeWorkspaceInviteResponse(w http.ResponseWriter) error
}

type RevokeWorkspaceInvite204Response struct {
}

func (response RevokeWorkspaceInvite204Response) VisitRevokeWorkspaceInviteResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type RevokeWorkspaceInvite403JSONResponse struct{ ErrorResponseJSONResponse }

func (response RevokeWorkspaceInvite403JSONResponse) VisitRevokeWorkspaceInviteResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type RevokeWorkspaceInvite404JSONResponse Error

func (response RevokeWorkspaceInvite404JSONResponse) VisitRevokeWorkspaceInviteResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type RevokeWorkspaceInvite500JSONResponse Error

func (response RevokeWorkspaceInvite500JSONResponse) VisitRevokeWorkspaceInviteResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type LeaveWorkspaceRequestObject struct {
	WorkspaceId uint `json:"workspaceId"`
	Params      LeaveWorkspaceParams
}

type LeaveWorkspaceResponseObject interface {
	VisitLeaveWorkspaceResponse(w http.ResponseWriter) error
}

type LeaveWorkspace204Response struct {
}

func (response LeaveWorkspace204Response) VisitLeaveWorkspaceResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type LeaveWorkspace403JSONResponse struct{ ErrorResponseJSONResponse }

func (response LeaveWorkspace403JSONResponse) VisitLeaveWorkspaceResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type LeaveWorkspace404JSONResponse Error

func (response LeaveWorkspace404JSONResponse) VisitLeaveWorkspaceResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type LeaveWorkspace500JSONResponse Error

func (response LeaveWorkspace500JSONResponse) VisitLeaveWorkspaceResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetWorkspaceMembersRequestObject struct {
	WorkspaceId uint `json:"workspaceId"`
	Params      GetWorkspaceMembersParams
}

type GetWorkspaceMembersResponseObject interface {
	VisitGetWorkspaceMembersResponse(w http.ResponseWriter) error
}

type GetWorkspaceMembers200JSONResponse []WorkspaceMemberResponse

func (response GetWorkspaceMembers200JSONResponse) VisitGetWorkspaceMembersResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetWorkspaceMembers403JSONResponse struct{ ErrorResponseJSONResponse }

func (response GetWorkspaceMembers403JSONResponse) VisitGetWorkspaceMembersResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type GetWorkspaceMembers404JSONResponse Error

func (response GetWorkspaceMembers404JSONResponse) VisitGetWorkspaceMembersResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type GetWorkspaceMembers500JSONResponse Error

func (response GetWorkspaceMembers500JSONResponse) VisitGetWorkspaceMembersResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type RemoveWorkspaceMemberRequestObject struct {
	WorkspaceId uint   `json:"workspaceId"`
	UserId      string `json:"userId"`
	Params      RemoveWorkspaceMemberParams
}

type RemoveWorkspaceMemberResponseObject interface {
	VisitRemoveWorkspaceMemberResponse(w http.ResponseWriter) error
}

type RemoveWorkspaceMember204Response struct {
}

func (response RemoveWorkspaceMember204Response) VisitRemoveWorkspaceMemberResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type RemoveWorkspaceMember403JSONResponse struct{ ErrorResponseJSONResponse }

func (response RemoveWorkspaceMember403JSONResponse) VisitRemoveWorkspaceMemberResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type RemoveWorkspaceMember404JSONResponse Error

func (response RemoveWorkspaceMember404JSONResponse) VisitRemoveWorkspaceMemberResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type RemoveWorkspaceMember500JSONResponse Error

func (response RemoveWorkspaceMember500JSONResponse) VisitRemoveWorkspaceMemberResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetWorkspaceTemplatesRequestObject struct {
	WorkspaceId uint `json:"workspaceId"`
	Params      GetWorkspaceTemplatesParams
}

type GetWorkspaceTemplatesResponseObject interface {
	VisitGetWorkspaceTemplatesResponse(w http.ResponseWriter) error
}

type GetWorkspaceTemplates200JSONResponse []TemplateResponse

func (response GetWorkspaceTemplates200JSONResponse) VisitGetWorkspaceTemplatesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetWorkspaceTemplates403JSONResponse struct{ ErrorResponseJSONResponse }

func (response GetWorkspaceTemplates403JSONResponse) VisitGetWorkspaceTemplatesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type GetWorkspaceTemplates404JSONResponse Error

func (response GetWorkspaceTemplates404JSONResponse) VisitGetWorkspaceTemplatesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type GetWorkspaceTemplates500JSONResponse Error

func (response GetWorkspaceTemplates500JSONResponse) VisitGetWorkspaceTemplatesResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Claim a workspace invite
	// (POST /api/v1/workspace-invites/{token}/claim)
	ClaimWorkspaceInvite(ctx context.Context, request ClaimWorkspaceInviteRequestObject) (ClaimWorkspaceInviteResponseObject, error)
	// Get all workspaces for current user
	// (GET /api/v1/workspaces)
	GetAllWorkspaces(ctx context.Context, request GetAllWorkspacesRequestObject) (GetAllWorkspacesResponseObject, error)
	// Create a new workspace
	// (POST /api/v1/workspaces)
	CreateWorkspace(ctx context.Context, request CreateWorkspaceRequestObject) (CreateWorkspaceResponseObject, error)
	// Delete workspace
	// (DELETE /api/v1/workspaces/{workspaceId})
	DeleteWorkspace(ctx context.Context, request DeleteWorkspaceRequestObject) (DeleteWorkspaceResponseObject, error)
	// Get workspace by ID
	// (GET /api/v1/workspaces/{workspaceId})
	GetWorkspaceById(ctx context.Context, request GetWorkspaceByIdRequestObject) (GetWorkspaceByIdResponseObject, error)
	// Update workspace
	// (PUT /api/v1/workspaces/{workspaceId})
	UpdateWorkspace(ctx context.Context, request UpdateWorkspaceRequestObject) (UpdateWorkspaceResponseObject, error)
	// Get checklists in a workspace
	// (GET /api/v1/workspaces/{workspaceId}/checklists)
	GetWorkspaceChecklists(ctx context.Context, request GetWorkspaceChecklistsRequestObject) (GetWorkspaceChecklistsResponseObject, error)
	// List active invite links for a workspace
	// (GET /api/v1/workspaces/{workspaceId}/invites)
	GetWorkspaceInvites(ctx context.Context, request GetWorkspaceInvitesRequestObject) (GetWorkspaceInvitesResponseObject, error)
	// Create a new workspace invite link
	// (POST /api/v1/workspaces/{workspaceId}/invites)
	CreateWorkspaceInvite(ctx context.Context, request CreateWorkspaceInviteRequestObject) (CreateWorkspaceInviteResponseObject, error)
	// Revoke a workspace invite link
	// (DELETE /api/v1/workspaces/{workspaceId}/invites/{inviteId})
	RevokeWorkspaceInvite(ctx context.Context, request RevokeWorkspaceInviteRequestObject) (RevokeWorkspaceInviteResponseObject, error)
	// Leave a workspace
	// (POST /api/v1/workspaces/{workspaceId}/leave)
	LeaveWorkspace(ctx context.Context, request LeaveWorkspaceRequestObject) (LeaveWorkspaceResponseObject, error)
	// Get workspace members
	// (GET /api/v1/workspaces/{workspaceId}/members)
	GetWorkspaceMembers(ctx context.Context, request GetWorkspaceMembersRequestObject) (GetWorkspaceMembersResponseObject, error)
	// Remove a member from workspace
	// (DELETE /api/v1/workspaces/{workspaceId}/members/{userId})
	RemoveWorkspaceMember(ctx context.Context, request RemoveWorkspaceMemberRequestObject) (RemoveWorkspaceMemberResponseObject, error)
	// Get templates in a workspace
	// (GET /api/v1/workspaces/{workspaceId}/templates)
	GetWorkspaceTemplates(ctx context.Context, request GetWorkspaceTemplatesRequestObject) (GetWorkspaceTemplatesResponseObject, error)
}

type StrictHandlerFunc = strictgin.StrictGinHandlerFunc
type StrictMiddlewareFunc = strictgin.StrictGinMiddlewareFunc

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
}

// ClaimWorkspaceInvite operation middleware
func (sh *strictHandler) ClaimWorkspaceInvite(ctx *gin.Context, token string, params ClaimWorkspaceInviteParams) {
	var request ClaimWorkspaceInviteRequestObject

	request.Token = token
	request.Params = params

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.ClaimWorkspaceInvite(ctx, request.(ClaimWorkspaceInviteRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ClaimWorkspaceInvite")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(ClaimWorkspaceInviteResponseObject); ok {
		if err := validResponse.VisitClaimWorkspaceInviteResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetAllWorkspaces operation middleware
func (sh *strictHandler) GetAllWorkspaces(ctx *gin.Context, params GetAllWorkspacesParams) {
	var request GetAllWorkspacesRequestObject

	request.Params = params

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetAllWorkspaces(ctx, request.(GetAllWorkspacesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetAllWorkspaces")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(GetAllWorkspacesResponseObject); ok {
		if err := validResponse.VisitGetAllWorkspacesResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateWorkspace operation middleware
func (sh *strictHandler) CreateWorkspace(ctx *gin.Context, params CreateWorkspaceParams) {
	var request CreateWorkspaceRequestObject

	request.Params = params

	var body CreateWorkspaceJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		ctx.Status(http.StatusBadRequest)
		ctx.Error(err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.CreateWorkspace(ctx, request.(CreateWorkspaceRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateWorkspace")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(CreateWorkspaceResponseObject); ok {
		if err := validResponse.VisitCreateWorkspaceResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeleteWorkspace operation middleware
func (sh *strictHandler) DeleteWorkspace(ctx *gin.Context, workspaceId uint, params DeleteWorkspaceParams) {
	var request DeleteWorkspaceRequestObject

	request.WorkspaceId = workspaceId
	request.Params = params

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteWorkspace(ctx, request.(DeleteWorkspaceRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteWorkspace")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(DeleteWorkspaceResponseObject); ok {
		if err := validResponse.VisitDeleteWorkspaceResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetWorkspaceById operation middleware
func (sh *strictHandler) GetWorkspaceById(ctx *gin.Context, workspaceId uint, params GetWorkspaceByIdParams) {
	var request GetWorkspaceByIdRequestObject

	request.WorkspaceId = workspaceId
	request.Params = params

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetWorkspaceById(ctx, request.(GetWorkspaceByIdRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetWorkspaceById")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(GetWorkspaceByIdResponseObject); ok {
		if err := validResponse.VisitGetWorkspaceByIdResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// UpdateWorkspace operation middleware
func (sh *strictHandler) UpdateWorkspace(ctx *gin.Context, workspaceId uint, params UpdateWorkspaceParams) {
	var request UpdateWorkspaceRequestObject

	request.WorkspaceId = workspaceId
	request.Params = params

	var body UpdateWorkspaceJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		ctx.Status(http.StatusBadRequest)
		ctx.Error(err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.UpdateWorkspace(ctx, request.(UpdateWorkspaceRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UpdateWorkspace")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(UpdateWorkspaceResponseObject); ok {
		if err := validResponse.VisitUpdateWorkspaceResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetWorkspaceChecklists operation middleware
func (sh *strictHandler) GetWorkspaceChecklists(ctx *gin.Context, workspaceId uint, params GetWorkspaceChecklistsParams) {
	var request GetWorkspaceChecklistsRequestObject

	request.WorkspaceId = workspaceId
	request.Params = params

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetWorkspaceChecklists(ctx, request.(GetWorkspaceChecklistsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetWorkspaceChecklists")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(GetWorkspaceChecklistsResponseObject); ok {
		if err := validResponse.VisitGetWorkspaceChecklistsResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetWorkspaceInvites operation middleware
func (sh *strictHandler) GetWorkspaceInvites(ctx *gin.Context, workspaceId uint, params GetWorkspaceInvitesParams) {
	var request GetWorkspaceInvitesRequestObject

	request.WorkspaceId = workspaceId
	request.Params = params

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetWorkspaceInvites(ctx, request.(GetWorkspaceInvitesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetWorkspaceInvites")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(GetWorkspaceInvitesResponseObject); ok {
		if err := validResponse.VisitGetWorkspaceInvitesResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateWorkspaceInvite operation middleware
func (sh *strictHandler) CreateWorkspaceInvite(ctx *gin.Context, workspaceId uint, params CreateWorkspaceInviteParams) {
	var request CreateWorkspaceInviteRequestObject

	request.WorkspaceId = workspaceId
	request.Params = params

	var body CreateWorkspaceInviteJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		ctx.Status(http.StatusBadRequest)
		ctx.Error(err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.CreateWorkspaceInvite(ctx, request.(CreateWorkspaceInviteRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateWorkspaceInvite")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(CreateWorkspaceInviteResponseObject); ok {
		if err := validResponse.VisitCreateWorkspaceInviteResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// RevokeWorkspaceInvite operation middleware
func (sh *strictHandler) RevokeWorkspaceInvite(ctx *gin.Context, workspaceId uint, inviteId uint, params RevokeWorkspaceInviteParams) {
	var request RevokeWorkspaceInviteRequestObject

	request.WorkspaceId = workspaceId
	request.InviteId = inviteId
	request.Params = params

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.RevokeWorkspaceInvite(ctx, request.(RevokeWorkspaceInviteRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "RevokeWorkspaceInvite")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(RevokeWorkspaceInviteResponseObject); ok {
		if err := validResponse.VisitRevokeWorkspaceInviteResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// LeaveWorkspace operation middleware
func (sh *strictHandler) LeaveWorkspace(ctx *gin.Context, workspaceId uint, params LeaveWorkspaceParams) {
	var request LeaveWorkspaceRequestObject

	request.WorkspaceId = workspaceId
	request.Params = params

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.LeaveWorkspace(ctx, request.(LeaveWorkspaceRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "LeaveWorkspace")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(LeaveWorkspaceResponseObject); ok {
		if err := validResponse.VisitLeaveWorkspaceResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetWorkspaceMembers operation middleware
func (sh *strictHandler) GetWorkspaceMembers(ctx *gin.Context, workspaceId uint, params GetWorkspaceMembersParams) {
	var request GetWorkspaceMembersRequestObject

	request.WorkspaceId = workspaceId
	request.Params = params

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetWorkspaceMembers(ctx, request.(GetWorkspaceMembersRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetWorkspaceMembers")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(GetWorkspaceMembersResponseObject); ok {
		if err := validResponse.VisitGetWorkspaceMembersResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// RemoveWorkspaceMember operation middleware
func (sh *strictHandler) RemoveWorkspaceMember(ctx *gin.Context, workspaceId uint, userId string, params RemoveWorkspaceMemberParams) {
	var request RemoveWorkspaceMemberRequestObject

	request.WorkspaceId = workspaceId
	request.UserId = userId
	request.Params = params

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.RemoveWorkspaceMember(ctx, request.(RemoveWorkspaceMemberRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "RemoveWorkspaceMember")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(RemoveWorkspaceMemberResponseObject); ok {
		if err := validResponse.VisitRemoveWorkspaceMemberResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetWorkspaceTemplates operation middleware
func (sh *strictHandler) GetWorkspaceTemplates(ctx *gin.Context, workspaceId uint, params GetWorkspaceTemplatesParams) {
	var request GetWorkspaceTemplatesRequestObject

	request.WorkspaceId = workspaceId
	request.Params = params

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetWorkspaceTemplates(ctx, request.(GetWorkspaceTemplatesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetWorkspaceTemplates")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(GetWorkspaceTemplatesResponseObject); ok {
		if err := validResponse.VisitGetWorkspaceTemplatesResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}
